/* 
  file summary: realistic maritime mock dataset for crew profiles, sea service historical vessel assignments, and stcw layer 1 & 2 certificates.
  responsibilities: populates initial store state with comprehensive crew member profiles and stcw compliance documentation registers.
  role in system: loaded by Zustand store (useMapStore.ts).
*/

import { CrewMember } from '../types/crew';

export const MOCK_CREW: CrewMember[] = [
  {
    id: 'CREW-101',
    fullName: 'Capt. Alexander Wright',
    rank: 'Master / Ship Captain',
    nationality: 'Australian',
    organization: 'Northwind Marine Pty Ltd',
    seamansBookNo: 'SB-AU-984102',
    passportNo: 'PA-AU-7739102',
    dateOfBirth: '1980-04-12',
    emergencyContact: '+61 412 345 678 (Spouse - Helen Wright)',
    currentVesselId: 'VESSEL-001',
    currentVesselName: 'MV Pacific Endeavour (IMO 9123456)',
    imageUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
    ],
    complianceStatus: 'Fully Compliant',
    overallComplianceScore: 96,
    lastAuditedDate: '2026-09-15',
    assignments: [
      {
        id: 'ASG-101',
        vesselId: 'VESSEL-001',
        vesselName: 'MV Pacific Endeavour',
        imoNumber: '9123456',
        vesselType: 'OSV / AHTS DP2',
        rankHeld: 'Master / Ship Captain',
        organization: 'Northwind Marine Pty Ltd',
        embarkDate: '2024-03-01',
        isCurrent: true,
      },
      {
        id: 'ASG-102',
        vesselId: 'VESSEL-002',
        vesselName: 'MV Southern Supporter',
        imoNumber: '9348120',
        vesselType: 'Offshore Support Vessel',
        rankHeld: 'Master / Ship Captain',
        embarkDate: '2021-06-15',
        disembarkDate: '2024-02-10',
        isCurrent: false,
      },
      {
        id: 'ASG-103',
        vesselId: 'VESSEL-003',
        vesselName: 'MV Ocean Guardian',
        imoNumber: '9481203',
        vesselType: 'Chemical / Oil Tanker',
        rankHeld: 'Chief Officer',
        embarkDate: '2018-02-01',
        disembarkDate: '2021-05-30',
        isCurrent: false,
      },
    ],
    layer1CoreDocuments: [
      {
        id: 'MAP-CRW-2026-IDNT-00101',
        title: 'Valid International Passport',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'SOLAS / National Regs',
        certificateNo: 'PA-AU-7739102',
        issuingAuthority: 'Australian Passport Office (DFAT)',
        issueDate: '2021-08-15',
        expiryDate: '2031-08-14',
        verificationStatus: 'Verified',
        fileName: 'passport_alexander_wright.pdf',
        fileSizeBytes: 1420000,
      },
      {
        id: 'MAP-CRW-2026-IDNT-00102',
        title: "National Seaman's Book (Continuous Discharge Certificate)",
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg I/9 / ILO 108',
        certificateNo: 'SB-AU-984102',
        issuingAuthority: 'Australian Maritime Safety Authority (AMSA)',
        issueDate: '2019-05-21',
        expiryDate: '2029-05-20',
        verificationStatus: 'Verified',
        fileName: 'seamans_book_wright.pdf',
        fileSizeBytes: 2150000,
      },
      {
        id: 'MAP-CRW-2026-STCW-00103',
        title: 'STCW Basic Safety Training (BST Refresher)',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg VI/1 (PSSR, PST, FPFF, EFA)',
        certificateNo: 'BST-2024-991',
        issuingAuthority: 'AMSA Approved Training Center',
        issueDate: '2024-03-16',
        expiryDate: '2029-03-15',
        verificationStatus: 'Verified',
        fileName: 'stcw_bst_wright_2024.pdf',
        fileSizeBytes: 980000,
      },
      {
        id: 'MAP-CRW-2026-MEDC-00104',
        title: 'ENG1 / ILO Maritime Medical Fitness Certificate',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg I/9 / MLC 2006',
        certificateNo: 'ENG1-2025-401',
        issuingAuthority: 'AMSA Authorized Medical Practitioner',
        issueDate: '2025-04-11',
        expiryDate: '2027-04-10',
        verificationStatus: 'Verified',
        fileName: 'eng1_medical_wright.pdf',
        fileSizeBytes: 840000,
      },
      {
        id: 'MAP-CRW-2026-STCW-00105',
        title: 'Security Awareness & Designated Security Duties',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg VI/6 (ISPS Code)',
        certificateNo: 'SEC-VI-6-88',
        issuingAuthority: 'AMSA Maritime Security Division',
        issueDate: '2024-03-16',
        expiryDate: '2029-03-15',
        verificationStatus: 'Verified',
        fileName: 'security_duties_wright.pdf',
        fileSizeBytes: 760000,
      },
    ],
    layer2Endorsements: [
      {
        id: 'MAP-CRW-2026-STCW-00106',
        title: 'Master Unlimited Certificate of Competency (CoC)',
        layer: 'Layer 2 - Vessel Specific & Endorsements',
        stcwRegulation: 'STCW Reg II/2 (Master > 3000 GT)',
        certificateNo: 'CoC-II-2-0041',
        issuingAuthority: 'Australian Maritime Safety Authority (AMSA)',
        flagState: 'Australia',
        issueDate: '2024-07-01',
        expiryDate: '2029-06-30',
        verificationStatus: 'Verified',
        fileName: 'coc_master_unlimited_wright.pdf',
        fileSizeBytes: 3100000,
      },
      {
        id: 'MAP-CRW-2026-STCW-00107',
        title: 'Flag State Endorsement (FSE / CRA)',
        layer: 'Layer 2 - Vessel Specific & Endorsements',
        stcwRegulation: 'STCW Reg I/10',
        certificateNo: 'FSE-AU-2024-11',
        issuingAuthority: 'AMSA Flag Administration',
        flagState: 'Australia',
        issueDate: '2024-07-01',
        expiryDate: '2029-06-30',
        verificationStatus: 'Verified',
        fileName: 'flag_state_endorsement_wright.pdf',
        fileSizeBytes: 1100000,
      },
      {
        id: 'MAP-CRW-2026-STCW-00108',
        title: 'Advanced Oil & Chemical Tanker Cargo Endorsement',
        layer: 'Layer 2 - Vessel Specific & Endorsements',
        stcwRegulation: 'STCW Reg V/1-1-2 (Advanced Oil & Chemical)',
        certificateNo: 'TNK-ADV-001',
        issuingAuthority: 'AMSA Maritime Academy',
        issueDate: '2023-11-16',
        expiryDate: '2028-11-15',
        verificationStatus: 'Verified',
        fileName: 'advanced_tanker_endorsement_wright.pdf',
        fileSizeBytes: 1850000,
      },
      {
        id: 'MAP-CRW-2026-STCW-00109',
        title: 'Kongsberg DP Operator Certificate (Unlimited)',
        layer: 'Layer 2 - Vessel Specific & Endorsements',
        stcwRegulation: 'STCW Reg V/1 / IMCA DP Standards',
        certificateNo: 'DPO-NI-99412',
        issuingAuthority: 'The Nautical Institute (NI UK)',
        issueDate: '2023-09-02',
        expiryDate: '2028-09-01',
        verificationStatus: 'Verified',
        fileName: 'dp_operator_unlimited_wright.pdf',
        fileSizeBytes: 2400000,
      },
      {
        id: 'MAP-CRW-2026-STCW-00110',
        title: 'Alternative Fuel IGF Code Training Certificate',
        layer: 'Layer 2 - Vessel Specific & Endorsements',
        stcwRegulation: 'STCW Reg V/3 (Low Flashpoint Fuels / LNG/IGF)',
        certificateNo: 'IGF-ADV-2024',
        issuingAuthority: 'AMSA Maritime Academy',
        issueDate: '2024-03-01',
        expiryDate: '2029-02-28',
        verificationStatus: 'Verified',
        fileName: 'igf_code_alternative_fuels_wright.pdf',
        fileSizeBytes: 1650000,
      },
    ],
  },
  {
    id: 'CREW-102',
    fullName: 'Chief Eng. Marcus Sterling',
    rank: 'Chief Engineer',
    nationality: 'Australian',
    seamansBookNo: 'SB-AU-883491',
    passportNo: 'PA-AU-6612984',
    dateOfBirth: '1982-09-24',
    emergencyContact: '+61 423 891 002 (Next of Kin - Sarah Sterling)',
    currentVesselId: 'VESSEL-002',
    currentVesselName: 'MV Coral Titan (IMO 9284710)',
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=800&q=80',
    ],
    complianceStatus: 'Fully Compliant',
    overallComplianceScore: 92,
    lastAuditedDate: '2026-09-12',
    assignments: [
      {
        id: 'ASG-201',
        vesselId: 'VESSEL-002',
        vesselName: 'MV Coral Titan',
        imoNumber: '9284710',
        vesselType: 'Offshore Support Vessel',
        rankHeld: 'Chief Engineer',
        embarkDate: '2023-01-10',
        isCurrent: true,
      },
      {
        id: 'ASG-202',
        vesselId: 'VESSEL-001',
        vesselName: 'MV Pacific Endeavour',
        imoNumber: '9123456',
        vesselType: 'OSV / AHTS DP2',
        rankHeld: 'Second Engineer',
        embarkDate: '2020-04-01',
        disembarkDate: '2022-12-15',
        isCurrent: false,
      },
    ],
    layer1CoreDocuments: [
      {
        id: 'MAP-CRW-2026-IDNT-00201',
        title: 'Valid International Passport',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'SOLAS / National Regs',
        certificateNo: 'PA-AU-6612984',
        issuingAuthority: 'Australian Passport Office',
        issueDate: '2020-03-10',
        expiryDate: '2030-03-09',
        verificationStatus: 'Verified',
        fileName: 'passport_marcus_sterling.pdf',
        fileSizeBytes: 1350000,
      },
      {
        id: 'MAP-CRW-2026-IDNT-00202',
        title: "National Seaman's Book (Continuous Discharge Certificate)",
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg I/9',
        certificateNo: 'SB-AU-883491',
        issuingAuthority: 'AMSA Australia',
        issueDate: '2018-11-12',
        expiryDate: '2028-11-11',
        verificationStatus: 'Verified',
        fileName: 'seamans_book_sterling.pdf',
        fileSizeBytes: 1980000,
      },
      {
        id: 'MAP-CRW-2026-STCW-00203',
        title: 'STCW Basic Safety Training',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg VI/1',
        certificateNo: 'BST-2023-881',
        issuingAuthority: 'AMSA Approved Center',
        issueDate: '2023-02-14',
        expiryDate: '2028-02-13',
        verificationStatus: 'Verified',
        fileName: 'bst_sterling.pdf',
        fileSizeBytes: 950000,
      },
      {
        id: 'MAP-CRW-2026-MEDC-00204',
        title: 'ENG1 Medical Fitness Certificate',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg I/9',
        certificateNo: 'ENG1-2025-902',
        issuingAuthority: 'AMSA Medical Practitioner',
        issueDate: '2025-06-01',
        expiryDate: '2027-05-31',
        verificationStatus: 'Verified',
        fileName: 'eng1_sterling.pdf',
        fileSizeBytes: 890000,
      },
      {
        id: 'MAP-CRW-2026-STCW-00205',
        title: 'Security Awareness Training',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg VI/6',
        certificateNo: 'SEC-VI-6-99',
        issuingAuthority: 'AMSA',
        issueDate: '2023-02-14',
        expiryDate: '2028-02-13',
        verificationStatus: 'Verified',
        fileName: 'security_sterling.pdf',
        fileSizeBytes: 720000,
      },
    ],
    layer2Endorsements: [
      {
        id: 'MAP-CRW-2026-STCW-00206',
        title: 'Chief Engineer Unlimited CoC',
        layer: 'Layer 2 - Vessel Specific & Endorsements',
        stcwRegulation: 'STCW Reg III/2 (Chief Engineer > 3000 kW)',
        certificateNo: 'CoC-III-2-8810',
        issuingAuthority: 'AMSA Australia',
        flagState: 'Australia',
        issueDate: '2022-10-01',
        expiryDate: '2027-09-30',
        verificationStatus: 'Verified',
        fileName: 'chief_engineer_coc_sterling.pdf',
        fileSizeBytes: 2900000,
      },
      {
        id: 'MAP-CRW-2026-STCW-00207',
        title: 'High Voltage Safety & Power Management',
        layer: 'Layer 2 - Vessel Specific & Endorsements',
        stcwRegulation: 'STCW Reg III/2 High Voltage',
        certificateNo: 'HV-2023-401',
        issuingAuthority: 'AMSA Engineering School',
        issueDate: '2023-04-10',
        expiryDate: '2028-04-09',
        verificationStatus: 'Verified',
        fileName: 'high_voltage_sterling.pdf',
        fileSizeBytes: 1450000,
      },
      {
        id: 'MAP-CRW-2026-STCW-00208',
        title: 'Alternative Fuel IGF Code Training (LNG Systems)',
        layer: 'Layer 2 - Vessel Specific & Endorsements',
        stcwRegulation: 'STCW Reg V/3 (Low Flashpoint Fuels)',
        certificateNo: 'IGF-ENG-2024',
        issuingAuthority: 'AMSA Maritime Academy',
        issueDate: '2024-05-15',
        expiryDate: '2029-05-14',
        verificationStatus: 'Verified',
        fileName: 'igf_eng_sterling.pdf',
        fileSizeBytes: 1550000,
      },
    ],
  },
  {
    id: 'CREW-103',
    fullName: 'Chief Off. Sarah Jenkins',
    rank: 'Chief Officer',
    nationality: 'Australian',
    seamansBookNo: 'SB-AU-771204',
    passportNo: 'PA-AU-5590412',
    dateOfBirth: '1987-11-05',
    emergencyContact: '+61 431 098 765 (Brother - David Jenkins)',
    currentVesselId: 'VESSEL-003',
    currentVesselName: 'MV Tasman Pioneer (IMO 9648102)',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?auto=format&fit=crop&w=800&q=80',
    ],
    complianceStatus: 'Expiring < 60 Days',
    overallComplianceScore: 78,
    lastAuditedDate: '2026-09-18',
    assignments: [
      {
        id: 'ASG-301',
        vesselId: 'VESSEL-003',
        vesselName: 'MV Tasman Pioneer',
        imoNumber: '9648102',
        vesselType: 'Chemical / Oil Tanker',
        rankHeld: 'Chief Officer',
        embarkDate: '2023-08-01',
        isCurrent: true,
      },
    ],
    layer1CoreDocuments: [
      {
        id: 'MAP-CRW-2026-IDNT-00301',
        title: 'Valid International Passport',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'SOLAS / National Regs',
        certificateNo: 'PA-AU-5590412',
        issuingAuthority: 'Australian Passport Office',
        issueDate: '2022-01-15',
        expiryDate: '2032-01-14',
        verificationStatus: 'Verified',
        fileName: 'passport_sarah_jenkins.pdf',
        fileSizeBytes: 1280000,
      },
      {
        id: 'MAP-CRW-2026-IDNT-00302',
        title: "National Seaman's Book (Continuous Discharge Certificate)",
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg I/9',
        certificateNo: 'SB-AU-771204',
        issuingAuthority: 'AMSA Australia',
        issueDate: '2020-04-18',
        expiryDate: '2030-04-17',
        verificationStatus: 'Verified',
        fileName: 'seamans_book_jenkins.pdf',
        fileSizeBytes: 2100000,
      },
      {
        id: 'MAP-CRW-2026-STCW-00303',
        title: 'ENG1 Medical Fitness Certificate',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg I/9',
        certificateNo: 'ENG1-2024-771',
        issuingAuthority: 'AMSA Authorized Practitioner',
        issueDate: '2024-11-01',
        expiryDate: '2026-10-31',
        verificationStatus: 'Expiring',
        fileName: 'eng1_jenkins_expiring.pdf',
        fileSizeBytes: 820000,
      },
      {
        id: 'MAP-CRW-2026-MEDC-00304',
        title: 'STCW Basic Safety Training',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg VI/1',
        certificateNo: 'BST-2022-401',
        issuingAuthority: 'AMSA Training Center',
        issueDate: '2022-06-10',
        expiryDate: '2027-06-09',
        verificationStatus: 'Verified',
        fileName: 'bst_jenkins.pdf',
        fileSizeBytes: 910000,
      },
    ],
    layer2Endorsements: [
      {
        id: 'MAP-CRW-2026-STCW-00305',
        title: 'Chief Officer CoC (STCW II/2)',
        layer: 'Layer 2 - Vessel Specific & Endorsements',
        stcwRegulation: 'STCW Reg II/2 (Chief Officer)',
        certificateNo: 'CoC-II-2-7740',
        issuingAuthority: 'AMSA Australia',
        flagState: 'Australia',
        issueDate: '2023-05-01',
        expiryDate: '2028-04-30',
        verificationStatus: 'Verified',
        fileName: 'coc_chief_officer_jenkins.pdf',
        fileSizeBytes: 2800000,
      },
      {
        id: 'MAP-CRW-2026-STCW-00306',
        title: 'Advanced Oil & Chemical Tanker Endorsement',
        layer: 'Layer 2 - Vessel Specific & Endorsements',
        stcwRegulation: 'STCW Reg V/1-1-2',
        certificateNo: 'TNK-ADV-902',
        issuingAuthority: 'AMSA Maritime Academy',
        issueDate: '2023-06-15',
        expiryDate: '2028-06-14',
        verificationStatus: 'Verified',
        fileName: 'tanker_endorsement_jenkins.pdf',
        fileSizeBytes: 1750000,
      },
    ],
  },
  {
    id: 'CREW-104',
    fullName: 'Bosun David Kowalski',
    rank: 'Bosun / Deck Foreman',
    nationality: 'Australian',
    organization: 'Gulf Security Services Pty Ltd',
    seamansBookNo: 'SB-AU-554109',
    passportNo: 'PA-AU-3310498',
    dateOfBirth: '1985-03-30',
    emergencyContact: '+61 411 223 344 (Wife - Anna Kowalski)',
    currentVesselId: 'VESSEL-001',
    currentVesselName: 'MV Pacific Endeavour (IMO 9123456)',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519764622345-23439dd774f7?auto=format&fit=crop&w=800&q=80',
    ],
    complianceStatus: 'Fully Compliant',
    overallComplianceScore: 100,
    lastAuditedDate: '2026-09-10',
    assignments: [
      {
        id: 'ASG-401',
        vesselId: 'VESSEL-001',
        vesselName: 'MV Pacific Endeavour',
        imoNumber: '9123456',
        vesselType: 'OSV / AHTS DP2',
        rankHeld: 'Bosun / Deck Foreman',
        embarkDate: '2023-05-10',
        isCurrent: true,
      },
    ],
    layer1CoreDocuments: [
      {
        id: 'MAP-CRW-2026-IDNT-00401',
        title: 'Valid International Passport',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'SOLAS / National Regs',
        certificateNo: 'PA-AU-3310498',
        issuingAuthority: 'Australian Passport Office',
        issueDate: '2021-02-20',
        expiryDate: '2031-02-19',
        verificationStatus: 'Verified',
        fileName: 'passport_kowalski.pdf',
        fileSizeBytes: 1100000,
      },
      {
        id: 'MAP-CRW-2026-IDNT-00402',
        title: "National Seaman's Book",
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg I/9',
        certificateNo: 'SB-AU-554109',
        issuingAuthority: 'AMSA Australia',
        issueDate: '2019-10-01',
        expiryDate: '2029-09-30',
        verificationStatus: 'Verified',
        fileName: 'seamans_book_kowalski.pdf',
        fileSizeBytes: 1800000,
      },
      {
        id: 'MAP-CRW-2026-STCW-00403',
        title: 'STCW Basic Safety Training',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg VI/1',
        certificateNo: 'BST-2023-110',
        issuingAuthority: 'AMSA Center',
        issueDate: '2023-01-15',
        expiryDate: '2028-01-14',
        verificationStatus: 'Verified',
        fileName: 'bst_kowalski.pdf',
        fileSizeBytes: 890000,
      },
      {
        id: 'MAP-CRW-2026-MEDC-00404',
        title: 'ENG1 Medical Fitness Certificate',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg I/9',
        certificateNo: 'ENG1-2025-112',
        issuingAuthority: 'AMSA Doctor',
        issueDate: '2025-08-10',
        expiryDate: '2027-08-09',
        verificationStatus: 'Verified',
        fileName: 'eng1_kowalski.pdf',
        fileSizeBytes: 810000,
      },
    ],
    layer2Endorsements: [
      {
        id: 'MAP-CRW-2026-STCW-00405',
        title: 'Able Seafarer Deck Certificate (STCW II/5)',
        layer: 'Layer 2 - Vessel Specific & Endorsements',
        stcwRegulation: 'STCW Reg II/5 (Able Seafarer Deck)',
        certificateNo: 'COP-II-5-991',
        issuingAuthority: 'AMSA Australia',
        issueDate: '2022-04-01',
        expiryDate: '2027-03-31',
        verificationStatus: 'Verified',
        fileName: 'cop_deck_kowalski.pdf',
        fileSizeBytes: 1600000,
      },
    ],
  },
  {
    id: 'CREW-105',
    fullName: 'Second Eng. Liam O\'Connor',
    rank: 'Second Engineer',
    nationality: 'Australian',
    seamansBookNo: 'SB-AU-440192',
    passportNo: 'PA-AU-2201948',
    dateOfBirth: '1990-06-18',
    emergencyContact: '+61 400 555 666 (Father - Patrick O\'Connor)',
    currentVesselId: 'VESSEL-002',
    currentVesselName: 'MV Coral Titan (IMO 9284710)',
    imageUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=800&q=80',
    photos: [
      'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&w=800&q=80',
    ],
    complianceStatus: 'Document Deficient',
    overallComplianceScore: 55,
    lastAuditedDate: '2026-09-01',
    assignments: [
      {
        id: 'ASG-501',
        vesselId: 'VESSEL-002',
        vesselName: 'MV Coral Titan',
        imoNumber: '9284710',
        vesselType: 'Offshore Support Vessel',
        rankHeld: 'Second Engineer',
        embarkDate: '2024-01-15',
        isCurrent: true,
      },
    ],
    layer1CoreDocuments: [
      {
        id: 'MAP-CRW-2026-IDNT-00501',
        title: 'Valid International Passport',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'SOLAS / National Regs',
        certificateNo: 'PA-AU-2201948',
        issuingAuthority: 'Australian Passport Office',
        issueDate: '2021-05-10',
        expiryDate: '2031-05-09',
        verificationStatus: 'Verified',
        fileName: 'passport_oconnor.pdf',
        fileSizeBytes: 1200000,
      },
      {
        id: 'MAP-CRW-2026-IDNT-00502',
        title: 'STCW Basic Safety Training (BST)',
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg VI/1',
        certificateNo: 'BST-2021-002',
        issuingAuthority: 'AMSA Training Center',
        issueDate: '2021-08-01',
        expiryDate: '2026-07-31', // Expired!
        verificationStatus: 'Expired',
        fileName: 'bst_oconnor_expired.pdf',
        fileSizeBytes: 890000,
      },
      {
        id: 'MAP-CRW-2026-STCW-00504',
        title: "National Seaman's Book (Continuous Discharge Certificate)",
        layer: 'Layer 1 - Universal Core',
        stcwRegulation: 'STCW Reg I/9',
        certificateNo: 'SB-AU-440192',
        issuingAuthority: 'AMSA Australia',
        issueDate: '2020-02-15',
        expiryDate: '2030-02-14',
        verificationStatus: 'Verified',
        fileName: 'seamans_book_oconnor.pdf',
        fileSizeBytes: 1850000,
      },
    ],
    layer2Endorsements: [
      {
        id: 'MAP-CRW-2026-MEDC-00503',
        title: 'Second Engineer CoC (STCW III/2)',
        layer: 'Layer 2 - Vessel Specific & Endorsements',
        stcwRegulation: 'STCW Reg III/2 (Second Engineer)',
        certificateNo: 'CoC-III-2-4019',
        issuingAuthority: 'AMSA Australia',
        issueDate: '2023-01-15',
        expiryDate: '2028-01-14',
        verificationStatus: 'Verified',
        fileName: 'coc_second_engineer_oconnor.pdf',
        fileSizeBytes: 2400000,
      },
    ],
  },
];
