/*
  file summary: mock equipment assets linked to fleet vessels.
  responsibilities: seeds initial equipment records for the asset hierarchy prototype.
  role in system: loaded by useMapStore on initialization.
*/

import { EquipmentAsset } from '../types/equipment';

const NOW = '2026-09-15T08:00:00.000Z';

export const MOCK_EQUIPMENT: EquipmentAsset[] = [
  {
    id: 'EQ-001',
    name: 'Fixed CO2 Fire Suppression System',
    equipmentIdentifier: 'FFE-PE-001',
    category: 'Fire-Fighting Equipment (FFE)',
    manufacturer: 'Novec / Minimax',
    model: 'MX-240 CO2 Bank',
    parentVesselId: 'VESSEL-001',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: null,
    imageUrl: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=80',
    ],
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'Surveyed',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Partially Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-002',
    name: 'ECDIS Navigation Suite',
    equipmentIdentifier: 'NAV-PE-002',
    category: 'Navigation & Bridge Equipment',
    manufacturer: 'Kongsberg',
    model: 'K-Bridge ECDIS',
    parentVesselId: 'VESSEL-001',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: null,
    imageUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=80',
    ],
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'In Class',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-003',
    name: 'Free-Fall Lifeboat #1',
    equipmentIdentifier: 'LSA-AO-001',
    category: 'Life-Saving Appliances',
    manufacturer: 'Schatt-Harding',
    model: 'FF 6.5',
    parentVesselId: 'VESSEL-002',
    owningOrganization: 'Pacific Ocean Logistics Pty Ltd',
    complianceReadinessScore: 70,
    imageUrl: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1000&q=80',
    ],
    availabilityStatus: 'On Charter',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'Survey Due',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Partially Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-004',
    name: 'Main Engine Port Side',
    equipmentIdentifier: 'MCH-AO-001',
    category: 'Machinery & Propulsion',
    manufacturer: 'Wärtsilä',
    model: '6L26',
    parentVesselId: 'VESSEL-002',
    owningOrganization: 'Pacific Ocean Logistics Pty Ltd',
    complianceReadinessScore: null,
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1581092162384-8987c1d64718?auto=format&fit=crop&w=1000&q=80',
    ],
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'In Class',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-005',
    name: 'Offshore Pedestal Crane #1 (150T Active Heave)',
    equipmentIdentifier: 'EQP-CRN-005',
    category: 'Machinery & Propulsion',
    manufacturer: 'Liebherr Offshore',
    model: 'RL-K 4200 Heavy Lift',
    parentVesselId: 'VESSEL-001',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: 100,
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1000&q=80',
    ],
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'In Class',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-006',
    name: 'Dynamic Positioning DP2 Console & FMEA Unit',
    equipmentIdentifier: 'EQP-DP2-006',
    category: 'Navigation & Bridge Equipment',
    manufacturer: 'Kongsberg Maritime',
    model: 'K-Pos DP-22 Dual Redundant',
    parentVesselId: 'VESSEL-001',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: null,
    imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1000&q=80',
    ],
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'In Class',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-007',
    name: 'Subsea Work-Class ROV & 150T Traction Winch',
    equipmentIdentifier: 'EQP-ROV-007',
    category: 'Machinery & Propulsion',
    manufacturer: 'Schilling Robotics / NOV',
    model: 'HD 150HP Deepwater SURF',
    parentVesselId: 'VESSEL-001',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: 85,
    imageUrl: 'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=80',
    ],
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'Surveyed',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Partially Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-008',
    name: 'Aviation Helideck Landing Platform & Foam Monitor',
    equipmentIdentifier: 'EQP-HLD-008',
    category: 'Life-Saving Appliances',
    manufacturer: 'Bayards Aluminium',
    model: 'CAP 437 / D-Value 21.0m',
    parentVesselId: 'VESSEL-001',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: null,
    imageUrl: 'https://images.unsplash.com/photo-1519074069444-1ba4ea16e91f?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1519074069444-1ba4ea16e91f?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?auto=format&fit=crop&w=1000&q=80',
    ],
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'In Class',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-009',
    name: 'Offshore Rigging, Slings & Spreader Bar Assembly',
    equipmentIdentifier: 'EQP-RIG-009',
    category: 'Machinery & Propulsion',
    manufacturer: 'Gunnebo Industries',
    model: 'DNV-ST-N001 Certified 250T Pad-Eyes',
    parentVesselId: 'VESSEL-002',
    owningOrganization: 'Woodside Energy Ltd',
    complianceReadinessScore: null,
    imageUrl: 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=80',
    ],
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'In Class',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-010',
    name: 'Survitec Decompression Chamber Spread',
    equipmentIdentifier: 'EQP-DCS-010',
    category: 'Other',
    manufacturer: 'Survitec Group',
    model: 'Twin-Lock 1800 Hyperbaric Chamber',
    parentVesselId: 'VESSEL-004',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: null,
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1000&q=80',
    ],
    availabilityStatus: 'Under Maintenance',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'Survey Due',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'In Progress',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-011',
    name: 'Fast Daughter Craft FRC-02',
    equipmentIdentifier: 'EQP-FRC-011',
    category: 'Life-Saving Appliances',
    manufacturer: 'Norsafe / Viking',
    model: 'Magnum 850 Twin Inboard',
    parentVesselId: 'VESSEL-006',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: null,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=1000&q=80',
    ],
    availabilityStatus: 'Unavailable',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'Overdue',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Non-Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-012',
    name: 'Hydraulic Shark Jaws & Towing Pins',
    equipmentIdentifier: 'EQP-SHK-012',
    category: 'Machinery & Propulsion',
    manufacturer: 'Karmøy Winch AS',
    model: 'Karm Fork 350T SWL',
    parentVesselId: 'VESSEL-005',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: null,
    imageUrl: 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1581092162384-8987c1d64718?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1000&q=80',
    ],
    availabilityStatus: 'Pending',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Pending Approval',
    registrationUpdatedAt: NOW,
    classStatus: 'Surveyed',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Partially Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-013',
    name: 'Subsea Gyrocompass & Acoustic Transceiver',
    equipmentIdentifier: 'EQP-NAV-013',
    category: 'Navigation & Bridge Equipment',
    manufacturer: 'Sonardyne',
    model: 'Compatt 6+ USBL Transceiver',
    parentVesselId: 'VESSEL-004',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: null,
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1000&q=80',
    photos: [
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1000&q=80',
    ],
    availabilityStatus: 'Unknown',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Draft',
    registrationUpdatedAt: NOW,
    classStatus: 'Uncertified',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Non-Compliant',
    complianceUpdatedAt: NOW,
  },
];
