/*
  file summary: mock equipment assets linked to fleet vessels.
  responsibilities: seeds initial equipment records for the asset hierarchy prototype.
  role in system: loaded by useMapStore on initialization.
*/

import { EquipmentAsset } from '../types/equipment';

const NOW = '2026-09-15T08:00:00.000Z';

export const MOCK_EQUIPMENT: EquipmentAsset[] = [
  {
    id: 'EQ-001',
    name: 'Fixed CO2 Fire Suppression System',
    equipmentIdentifier: 'FFE-PE-001',
    category: 'Fire-Fighting Equipment (FFE)',
    manufacturer: 'Novec / Minimax',
    model: 'MX-240 CO2 Bank',
    parentVesselId: 'VESSEL-001',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: 85,
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'Surveyed',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Partially Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-002',
    name: 'ECDIS Navigation Suite',
    equipmentIdentifier: 'NAV-PE-002',
    category: 'Navigation & Bridge Equipment',
    manufacturer: 'Kongsberg',
    model: 'K-Bridge ECDIS',
    parentVesselId: 'VESSEL-001',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: 100,
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'In Class',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-003',
    name: 'Free-Fall Lifeboat #1',
    equipmentIdentifier: 'LSA-AO-001',
    category: 'Life-Saving Appliances',
    manufacturer: 'Schatt-Harding',
    model: 'FF 6.5',
    parentVesselId: 'VESSEL-002',
    owningOrganization: 'Pacific Ocean Logistics Pty Ltd',
    complianceReadinessScore: 70,
    availabilityStatus: 'On Charter',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'Survey Due',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Partially Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-004',
    name: 'Main Engine Port Side',
    equipmentIdentifier: 'MCH-AO-001',
    category: 'Machinery & Propulsion',
    manufacturer: 'Wärtsilä',
    model: '6L26',
    parentVesselId: 'VESSEL-002',
    owningOrganization: 'Pacific Ocean Logistics Pty Ltd',
    complianceReadinessScore: 90,
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'In Class',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-005',
    name: 'Offshore Pedestal Crane #1 (150T Active Heave)',
    equipmentIdentifier: 'EQP-CRN-005',
    category: 'Machinery & Propulsion',
    manufacturer: 'Liebherr Offshore',
    model: 'RL-K 4200 Heavy Lift',
    parentVesselId: 'VESSEL-001',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: 98,
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'In Class',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-006',
    name: 'Dynamic Positioning DP2 Console & FMEA Unit',
    equipmentIdentifier: 'EQP-DP2-006',
    category: 'Navigation & Bridge Equipment',
    manufacturer: 'Kongsberg Maritime',
    model: 'K-Pos DP-22 Dual Redundant',
    parentVesselId: 'VESSEL-001',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: 100,
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'In Class',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-007',
    name: 'Subsea Work-Class ROV & 150T Traction Winch',
    equipmentIdentifier: 'EQP-ROV-007',
    category: 'Machinery & Propulsion',
    manufacturer: 'Schilling Robotics / NOV',
    model: 'HD 150HP Deepwater SURF',
    parentVesselId: 'VESSEL-001',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: 95,
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'Surveyed',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-008',
    name: 'Aviation Helideck Landing Platform & Foam Monitor',
    equipmentIdentifier: 'EQP-HLD-008',
    category: 'Life-Saving Appliances',
    manufacturer: 'Bayards Aluminium',
    model: 'CAP 437 / D-Value 21.0m',
    parentVesselId: 'VESSEL-001',
    owningOrganization: 'Northwind Marine Pty Ltd',
    complianceReadinessScore: 100,
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'In Class',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Compliant',
    complianceUpdatedAt: NOW,
  },
  {
    id: 'EQ-009',
    name: 'Offshore Rigging, Slings & Spreader Bar Assembly',
    equipmentIdentifier: 'EQP-RIG-009',
    category: 'Machinery & Propulsion',
    manufacturer: 'Gunnebo Industries',
    model: 'DNV-ST-N001 Certified 250T Pad-Eyes',
    parentVesselId: 'VESSEL-002',
    owningOrganization: 'Woodside Energy Ltd',
    complianceReadinessScore: 94,
    availabilityStatus: 'Available',
    availabilityUpdatedAt: NOW,
    registrationStatus: 'Registered',
    registrationUpdatedAt: NOW,
    classStatus: 'In Class',
    classStatusUpdatedAt: NOW,
    complianceStatus: 'Compliant',
    complianceUpdatedAt: NOW,
  },
];
