/* 
  file summary: centralized mock dataset for service provider marketplace offerings (vessels, equipment, crew, services).
  responsibilities: provides verified third-party maritime assets and service offerings for chartering, leasing, and engagement.
  role in system: loaded by marketplaceHelpers.ts and useMapStore.ts.
*/

import { MarketplaceItem } from '../types/marketplace';

export const MOCK_MARKETPLACE_ITEMS: MarketplaceItem[] = [
  // 1. Service Provider Vessels
  {
    id: 'MAP-VES-2026-MKT-00008',
    name: 'MV Meridian Pioneer',
    category: 'vessel',
    subcategory: 'PSV / Multipurpose',
    providerOrg: 'Meridian Marine Services Pty Ltd',
    location: 'Darwin, NT',
    availabilityStatus: 'Available for Charter',
    availabilityTagColor: '#059669',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1661879449050-069f67e200bd?q=80&w=1122&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    shortDescription: 'High-capacity DP2 platform supply vessel fitted for bulk mud, deck cargo, and offshore support.',
    metrics: [
      { label: 'Capacity (DWT)', value: '4,200 MT' },
      { label: 'Assurance / Class', value: 'DNV · 85% Ready' },
    ],
    complianceReadinessScore: 85,
    rateEstimate: 'AUD 28,500 / day',
    mobilizationLeadTime: '48 Hours',
    certifications: ['DNV +100A1 DP2', 'AMSA Statutory Pack', 'SOLAS / ISPS Fully Certified'],
    operationalCapabilities: [
      'Deck cargo area 850 m2 with 10t/m2 loading strength',
      'Dynamic Positioning DP2 (Kongsberg K-Pos 22)',
      'Dual fuel low-sulphur compliant propulsion (2x 2,600 kW)',
      'Liquid mud and dry bulk pneumatic discharge systems',
    ],
    detailedSpecs: [
      { label: 'IMO Number', value: '9845120' },
      { label: 'Classification', value: 'DNV +100A1 PSV DP2' },
      { label: 'Year Built', value: '2022 (Vard Marine Norway)' },
      { label: 'Length Overall (LOA)', value: '84.5 m' },
      { label: 'Beam / Draft', value: '19.0 m / 5.9 m' },
      { label: 'Gross Tonnage', value: '3,400 GT' },
      { label: 'Deadweight Tonnage', value: '4,200 MT' },
      { label: 'Clear Deck Area', value: '850 m2' },
      { label: 'DP Capability', value: 'DP Class 2 (Kongsberg)' },
      { label: 'Accommodation', value: '32 Berths (Fully Air-Conditioned)' },
    ],
    contact: {
      name: 'Jonathan Briggs',
      role: 'Fleet Commercial Director · Meridian Marine',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      email: 'chartering@meridianmarine.com.au',
      phone: '+61 8 8981 4455',
    },
    linkedEntityId: 'VESSEL-008',
    linkedEntityType: 'vessel',
  },
  {
    id: 'MAP-VES-2026-MKT-00009',
    name: 'MV Austral Horizon',
    category: 'vessel',
    subcategory: 'PSV / Deck & Liquid Cargo',
    providerOrg: 'Austral Ocean Shipping Ltd',
    location: 'Fremantle, WA',
    availabilityStatus: 'Available for Charter',
    availabilityTagColor: '#059669',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1661962278758-d529030366fb?q=80&w=1228&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    shortDescription: 'Modern offshore supply vessel with advanced liquid mud management and dual bow thrusters.',
    metrics: [
      { label: 'Capacity (DWT)', value: '4,800 MT' },
      { label: 'Assurance / Class', value: "Lloyd's Register · 90% Ready" },
    ],
    complianceReadinessScore: 90,
    rateEstimate: 'AUD 31,000 / day',
    mobilizationLeadTime: '24 Hours',
    certifications: ["Lloyd's Register +100A1", 'IOPP Tier III Compliant', 'AMSA Safety Construction'],
    operationalCapabilities: [
      'Large clear deck area 920 m2 with heavy container fittings',
      'Converteam Dynamic Positioning DP2 Suite',
      'Automated tank washing and toxic vapor recovery',
      'Full FiFi 1 firefighting water spray monitors',
    ],
    detailedSpecs: [
      { label: 'IMO Number', value: '9782143' },
      { label: 'Classification', value: "Lloyd's Register +100A1 DP2" },
      { label: 'Year Built', value: '2021 (Damen Shipyards)' },
      { label: 'Length Overall (LOA)', value: '89.2 m' },
      { label: 'Beam / Draft', value: '20.0 m / 6.2 m' },
      { label: 'Gross Tonnage', value: '4,100 GT' },
      { label: 'Deadweight Tonnage', value: '4,800 MT' },
      { label: 'Deck Load Capacity', value: '2,200 MT' },
      { label: 'DP Capability', value: 'DP Class 2 (Converteam)' },
      { label: 'Accommodation', value: '28 Berths' },
    ],
    contact: {
      name: 'Elena Rostova',
      role: 'Commercial Operations Lead · Austral Ocean',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
      email: 'charter@australocean.com.au',
      phone: '+61 8 9335 8820',
    },
    linkedEntityId: 'VESSEL-009',
    linkedEntityType: 'vessel',
  },
  {
    id: 'MAP-VES-2026-MKT-00010',
    name: 'MV Oceanic Sentinel',
    category: 'vessel',
    subcategory: 'AHTS / Towing',
    providerOrg: 'Oceanic Horizon Logistics Pty Ltd',
    location: 'Dampier, WA',
    availabilityStatus: 'Available for Charter',
    availabilityTagColor: '#059669',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1664298003939-e93f37196118?q=80&w=1333&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    shortDescription: 'Anchor handling tug supply vessel with 180T continuous bollard pull for rig moves.',
    metrics: [
      { label: 'Bollard Pull', value: '180 MT' },
      { label: 'Assurance / Class', value: 'ABS · 75% Ready' },
    ],
    complianceReadinessScore: 75,
    rateEstimate: 'AUD 34,500 / day',
    mobilizationLeadTime: '72 Hours',
    certifications: ['ABS +A1 AHTS DP2', 'IMCA Rig Move Vetted', 'SOLAS / ISPS Certified'],
    operationalCapabilities: [
      'Continuous bollard pull 180 MT with 400T brake anchor handling winch',
      'Kongsberg K-Pos DP2 integrated joystick system',
      'Hydraulic shark jaws and towing pins (350T SWL)',
      'Heavy offshore anchor recovery and rig repositioning',
    ],
    detailedSpecs: [
      { label: 'IMO Number', value: '9651892' },
      { label: 'Classification', value: 'ABS +A1 Offshore Support Vessel (AHTS) DP2' },
      { label: 'Year Built', value: '2020 (Keppel FELS)' },
      { label: 'Length Overall (LOA)', value: '82.0 m' },
      { label: 'Beam / Draft', value: '18.5 m / 5.7 m' },
      { label: 'Gross Tonnage', value: '3,300 GT' },
      { label: 'Bollard Pull', value: '180 MT Continuous' },
      { label: 'Towing Winch', value: 'Brattvaag Double Drum 400T' },
      { label: 'DP Capability', value: 'DP Class 2 (Kongsberg K-Pos)' },
      { label: 'Accommodation', value: '30 Berths' },
    ],
    contact: {
      name: 'Justin Franci',
      role: 'Senior Marine Broker · Oceanic Horizon',
      avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80',
      email: 'brokerage@oceanichorizon.com.au',
      phone: '+61 8 9183 9900',
    },
    linkedEntityId: 'VESSEL-010',
    linkedEntityType: 'vessel',
  },

  // 2. Service Provider Equipment
  {
    id: 'MAP-EQP-2026-MKT-00101',
    name: 'Schilling HD 150HP Work-Class ROV System',
    category: 'equipment',
    subcategory: 'Subsea Robotics & Intervention',
    providerOrg: 'Subsea 7 Engineering & Robotics',
    location: 'Dampier Shorebase, WA',
    availabilityStatus: 'Mobilization Ready',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?auto=format&fit=crop&w=1000&q=80',
    shortDescription: 'Deepwater heavy work-class ROV spread with 3,000m depth rating and dual manipulator arms.',
    metrics: [
      { label: 'Depth Rating', value: '3,000 MSW' },
      { label: 'Power / Payload', value: '150 HP · 250 kg' },
    ],
    complianceReadinessScore: 98,
    rateEstimate: 'AUD 8,200 / day spread',
    mobilizationLeadTime: '3 Days',
    certifications: ['IMCA R004 Compliant', 'DNV Lifting Appliance Survey', 'ISO 13628-8 Subsea Standard'],
    operationalCapabilities: [
      'Dual 7-function Schilling Titan 4 spatial manipulator arms',
      'Dedicated Top-Hat TMS (Tether Management System) with 800m tether',
      'High-definition multibeam imaging sonar and HD digital video cameras',
      'Hydraulic torque tool, hot stabs, and cutter tool spreads included',
    ],
    detailedSpecs: [
      { label: 'System Type', value: 'Heavy Work-Class Hydraulic ROV' },
      { label: 'Depth Rating', value: '3,000 meters sea water (MSW)' },
      { label: 'Hydraulic Power Unit', value: '150 HP (112 kW) Curvetech' },
      { label: 'Payload Capacity', value: '250 kg in air' },
      { label: 'Tether Length', value: '800 m excursion from TMS' },
      { label: 'Control Van', value: 'DNV 2.7-1 Zone 2 Certified Control Container' },
      { label: 'LARS Winch', value: 'Active Heave Compensated A-Frame Winch' },
      { label: 'Inspection Tooling', value: 'Class 1-4 Torque Tool, CP Probe, Laser Scaler' },
    ],
    contact: {
      name: 'Dr. Alistair MacIntyre',
      role: 'Subsea Operations Manager · Subsea 7',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
      email: 'subsea.tooling@subsea7.com',
      phone: '+61 8 9485 7100',
    },
  },
  {
    id: 'MAP-EQP-2026-MKT-00102',
    name: 'Liebherr RL-K 4200 150T Active Heave Offshore Crane',
    category: 'equipment',
    subcategory: 'Machinery & Heavy Lifting',
    providerOrg: 'Boskalis Heavy Marine Transport',
    location: 'Henderson Facility, WA',
    availabilityStatus: 'Available for Lease',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1000&q=80',
    shortDescription: 'Pedestal-mounted knuckle boom crane with active heave compensation for subsea construction.',
    metrics: [
      { label: 'Max Capacity', value: '150 MT SWL' },
      { label: 'Boom Outreach', value: '45.0 Meters' },
    ],
    complianceReadinessScore: 96,
    rateEstimate: 'AUD 12,000 / day',
    mobilizationLeadTime: '5 Days',
    certifications: ['DNVGL-ST-0378 Lifting Appliances', 'EN 13852-1 Offshore Cranes', 'AMSA Class Surveyed'],
    operationalCapabilities: [
      'Active Heave Compensation (AHC) down to 2,500m subsea water depth',
      'Knuckle boom design for minimal pendulum motion on heavy offshore decks',
      'Integrated auxiliary whip hoist with 20 MT SWL at 52m reach',
      'Fail-safe overload protection and real-time boom angle monitoring',
    ],
    detailedSpecs: [
      { label: 'Manufacturer', value: 'Liebherr Offshore Cranes' },
      { label: 'Model', value: 'RL-K 4200 Heavy Construction' },
      { label: 'Main Hoist SWL', value: '150 MT @ 14 m radius' },
      { label: 'Max Radius SWL', value: '35 MT @ 45 m radius' },
      { label: 'Subsea Wire Capacity', value: '2,500 m non-rotating wire rope' },
      { label: 'Heave Compensation', value: 'Active Electro-Hydraulic (AHC)' },
      { label: 'Pedestal Diameter', value: '3.8 m standard flange' },
      { label: 'Power Consumption', value: '3x 350 kW integrated power pack' },
    ],
    contact: {
      name: 'Willem Van Dijk',
      role: 'Heavy Lifting Asset Manager · Boskalis',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      email: 'cranes@boskalis.com.au',
      phone: '+61 8 9437 2200',
    },
  },
  {
    id: 'MAP-EQP-2026-MKT-00103',
    name: 'Kongsberg K-Pos DP-22 Dual Redundant DP Unit',
    category: 'equipment',
    subcategory: 'Navigation & Bridge Systems',
    providerOrg: 'Kongsberg Maritime Services',
    location: 'Perth Tech Depot, WA',
    availabilityStatus: 'In Stock / Ready',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=1000&q=80',
    shortDescription: 'Complete standalone DP2 operator station and dual controller cabinet with DGPS sensors.',
    metrics: [
      { label: 'Redundancy', value: 'Dual Class 2' },
      { label: 'Compliance', value: 'IMO Class II / DP2' },
    ],
    complianceReadinessScore: 100,
    rateEstimate: 'AUD 3,500 / day (Lease)',
    mobilizationLeadTime: '24 Hours',
    certifications: ['DNV Class Notation DP-2', 'ABS Class 2 Certified', 'IMO MSC/Circ.645 Guideline'],
    operationalCapabilities: [
      'Dual controller architecture with bumpless transfer on fault detection',
      'Integrated CyScan laser and HiPAP 502 acoustic positioning inputs',
      'Dual multi-constellation Fugro Marinestar GNSS receivers',
      'Standardized interface for Rolls-Royce, Wärtsilä, and Schottel thrusters',
    ],
    detailedSpecs: [
      { label: 'System Series', value: 'Kongsberg K-Pos Generation 7' },
      { label: 'Hardware Architecture', value: 'Dual Redundant VME Controllers' },
      { label: 'Operator Stations', value: '2x 24-inch TFT Touch Consoles' },
      { label: 'Reference Inputs', value: '2x DGPS, 1x Laser, 1x Acoustic, 3x MRU' },
      { label: 'Wind Sensors', value: '3x Ultrasonic Wind Sensors with De-Icing' },
      { label: 'Power Supply', value: 'Dual 24V DC / 230V AC UPS Buffered' },
    ],
    contact: {
      name: 'Kari Lindqvist',
      role: 'Maritime Systems Engineer · Kongsberg',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
      email: 'support.dp@kongsberg.com',
      phone: '+61 8 9486 0100',
    },
  },

  // 3. Service Provider Crew
  {
    id: 'MAP-CRW-2026-MKT-00201',
    name: 'Capt. Callum Sterling',
    category: 'crew',
    subcategory: 'Master Mariner / Unlimited DP',
    providerOrg: 'Atlas Professionals Marine Crewing',
    location: 'Perth, WA (Available Worldwide)',
    availabilityStatus: 'Available Immediately',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    shortDescription: 'Senior Master Mariner with 16 years command experience on large AHTS and construction vessels.',
    metrics: [
      { label: 'Rank / Grade', value: 'Master Unlimited' },
      { label: 'STCW Compliance', value: '100% · Valid to 2031' },
    ],
    complianceReadinessScore: 98,
    rateEstimate: 'Day Rate on Application',
    mobilizationLeadTime: '24 Hours',
    certifications: ['Master Mariner (STCW II/2)', 'Nautical Institute DP Unlimited', 'BOSIET / OPITO Offshore Safety', 'BHP / Chevron Marine Inducted'],
    operationalCapabilities: [
      'Over 4,500 logged hours on DP2 / DP3 construction and anchor handling operations',
      'Extensive FPSO offloading, tandem mooring, and heavy subsea installation experience',
      'Advanced ship-handling instructor for dynamic positioning simulation centers',
      'Full Australian AMSA and UK MCA Certificate of Competency (CoC)',
    ],
    detailedSpecs: [
      { label: 'Nationality', value: 'Australian' },
      { label: 'Seamans Book', value: 'AMSA SB-AU-448102' },
      { label: 'Medical Clearance', value: 'AMSA Marine Medical (Valid to 2028)' },
      { label: 'DP Certificate No.', value: 'NI-DP-UNL-99214' },
      { label: 'Total Sea Service', value: '16 Years (11 Years in Command)' },
      { label: 'Primary Vessel Types', value: 'AHTS, PSV, SSV, Cable Layer' },
    ],
    contact: {
      name: 'Sarah O’Reilly',
      role: 'Senior Marine Crewing Manager · Atlas Professionals',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
      email: 'crewing.wa@atlasprofessionals.com.au',
      phone: '+61 8 9214 7700',
    },
  },
  {
    id: 'MAP-CRW-2026-MKT-00202',
    name: 'Henrik Vestergaard',
    category: 'crew',
    subcategory: 'Chief Engineer / High-Voltage Certified',
    providerOrg: 'Brunel International Marine Staffing',
    location: 'Fremantle, WA',
    availabilityStatus: 'Available Next Week',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80',
    shortDescription: 'Chief Engineer specializing in diesel-electric dual-fuel propulsion and DP3 power management.',
    metrics: [
      { label: 'Rank / Grade', value: 'Chief Engineer (III/2)' },
      { label: 'STCW Compliance', value: '100% · Valid to 2030' },
    ],
    complianceReadinessScore: 95,
    rateEstimate: 'Standard Tier Rate',
    mobilizationLeadTime: '48 Hours',
    certifications: ['STCW III/2 Chief Engineer Unlimited', 'High Voltage Safety (6.6 kV / 11 kV)', 'Wärtsilä & Rolls-Royce Certified', 'OPITO HUET / CA-EBS'],
    operationalCapabilities: [
      'Over 14 years managing complex diesel-electric automation and thruster maintenance',
      'Expert in closed-bus DP power management system troubleshooting and FMEA verification',
      'Advanced drydocking engineering lead for multi-engine complete overhauls',
      'Fluent in computerized maintenance management systems (AMOS, StarIPS)',
    ],
    detailedSpecs: [
      { label: 'Nationality', value: 'Danish (Australian Permanent Resident)' },
      { label: 'Seamans Book', value: 'DK-SB-88201 / AMSA Endorsed' },
      { label: 'Medical Clearance', value: 'OGUK & AMSA Medical Valid' },
      { label: 'Power Systems', value: '6.6 kV High Voltage Diesel-Electric' },
      { label: 'Total Sea Service', value: '14 Years' },
      { label: 'Primary Vessel Types', value: 'DP3 SSV, Pipelay, Drillships' },
    ],
    contact: {
      name: 'Mark Jansen',
      role: 'Offshore Technical Recruiter · Brunel Marine',
      avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80',
      email: 'marine.perth@brunel.net',
      phone: '+61 8 9429 5600',
    },
  },

  // 4. Service Provider Turnkey Services
  {
    id: 'MAP-SRV-2026-MKT-00301',
    name: 'Annual DP FMEA Proving Trials & Gap Analysis',
    category: 'service',
    subcategory: 'Marine Assurance & Technical Auditing',
    providerOrg: 'Global Maritime Assurance Group',
    location: 'Perth & North West Shelf, WA',
    availabilityStatus: 'Booking Available',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1000&q=80',
    shortDescription: 'Comprehensive IMCA M190/M166 DP FMEA annual trials, power failure verification, and class endorsement.',
    metrics: [
      { label: 'Standard', value: 'IMCA M190 / IMO DP2' },
      { label: 'Turnaround', value: '5-Day Full Report' },
    ],
    complianceReadinessScore: 100,
    rateEstimate: 'AUD 22,000 / Campaign',
    mobilizationLeadTime: '3 Days Notice',
    certifications: ['IMCA Accredited DP Practitioner', 'DNV Approved Service Supplier', 'ISO 9001:2015 Marine Auditing'],
    operationalCapabilities: [
      'Comprehensive vessel electrical single point failure and blackout recovery trials',
      'Thorough closed-bus tie-breaker fault simulation and thruster response validation',
      'Fast-track compliance dossier delivery for client assurance set approval gates',
      'Onboard attendance by Master Mariner and Senior DP Technical Auditor',
    ],
    detailedSpecs: [
      { label: 'Scope Standard', value: 'IMCA M190 Rev 3 & IMCA M166 Guidelines' },
      { label: 'Survey Duration', value: '1 to 2 Days Onboard Trials' },
      { label: 'Deliverables', value: 'Executive DP Trial Report, Gap Matrix, Signed Class CoC' },
      { label: 'Supported Classes', value: 'DNV, Lloyd’s Register, ABS, Bureau Veritas' },
      { label: 'Target Vessels', value: 'DP Class 1, Class 2, and Class 3 Offshore Vessels' },
    ],
    contact: {
      name: 'David Sutherland',
      role: 'Principal DP Consultant · Global Maritime',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      email: 'dp.assurance@globalmaritime.com',
      phone: '+61 8 9268 4000',
    },
  },
  {
    id: 'MAP-SRV-2026-MKT-00302',
    name: 'Subsea High-Resolution Multibeam Bathymetry & Seabed Survey',
    category: 'service',
    subcategory: 'Geophysical & Hydrographic Survey',
    providerOrg: 'Fugro Marine Survey & Geospatial',
    location: 'Dampier / Port Hedland / Darwin Base',
    availabilityStatus: 'Spread Ready',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1000&q=80',
    shortDescription: 'High-resolution pipeline route surveying, side-scan sonar debris clearing, and bathymetric mapping.',
    metrics: [
      { label: 'Resolution', value: '0.05 m Grid Depth' },
      { label: 'Sensor Spread', value: 'Kongsberg EM2040' },
    ],
    complianceReadinessScore: 98,
    rateEstimate: 'Project Quote Basis',
    mobilizationLeadTime: '48 Hours',
    certifications: ['IHO S-44 Order 1a Standard', 'Fugro Starfix GNSS Precise Positioning', 'AMSA Hydrographic Office Approved'],
    operationalCapabilities: [
      'Dual-head Kongsberg EM2040 multibeam echo sounder for ultra-high density point clouds',
      'Edgetech 4200 high-frequency side-scan sonar for seabed anomaly and debris detection',
      'Real-time automated GIS charting and sub-bottom acoustic profiling',
      'Packaged spread suitable for rapid mobilization on chartered client vessels',
    ],
    detailedSpecs: [
      { label: 'Survey Suite', value: 'Kongsberg EM2040 Dual Multibeam + Edgetech Sonar' },
      { label: 'Depth Range', value: '2 m to 600 m water depth' },
      { label: 'Output Formats', value: 'GeoTIFF, XYZ Point Clouds, DTM, CAD DWG, PDF Charts' },
      { label: 'Survey Team', value: '2x Hydrographic Surveyors + 1x Data Processor' },
    ],
    contact: {
      name: 'Claire Thornton',
      role: 'Commercial Lead · Fugro Marine Survey',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
      email: 'marine.quotes@fugro.com.au',
      phone: '+61 8 9437 8888',
    },
  },
  {
    id: 'MAP-SRV-2026-MKT-00303',
    name: 'Marine Warranty Surveying (MWS) & Rig Move Attendance',
    category: 'service',
    subcategory: 'Marine Warranty & Insurance Risk Survey',
    providerOrg: 'AqualisBraemar LOC Energy & Marine',
    location: 'Perth & Offshore Facilities, WA',
    availabilityStatus: 'Surveyors on Standby',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1000&q=80',
    shortDescription: 'Independent third-party warranty surveying, certificate of approval (CoA) issuance for jackup and semi-sub rig moves.',
    metrics: [
      { label: 'Accreditation', value: 'SOMWS / Lloyd’s Vetted' },
      { label: 'Coverage', value: '24/7 Offshore Deployment' },
    ],
    complianceReadinessScore: 100,
    rateEstimate: 'AUD 3,800 / day + disbursements',
    mobilizationLeadTime: '12 Hours',
    certifications: ['SOMWS Accredited MWS Surveyors', 'Joint Rig Committee (JRC) Approved', 'ISO/IEC 17020 Inspection Authority'],
    operationalCapabilities: [
      'Engineering desktop review of towing calculations, anchor patterns, and metocean criteria',
      'Onsite physical inspection of towing bridles, delta plates, and vessel suitability',
      'Formal issuance of Certificate of Approval (CoA) prior to vessel departure or anchor laying',
      'Emergency standby marine consultants for weather routing and complex mooring operations',
    ],
    detailedSpecs: [
      { label: 'Scope of Service', value: 'Marine Warranty Surveying & Certificate of Approval' },
      { label: 'Standards Applied', value: 'DNV-ST-N001 Marine Operations & JRC Guidelines' },
      { label: 'Surveyor Grade', value: 'Master Mariner / Naval Architect (Minimum 12 Yrs Exp)' },
      { label: 'Report Delivery', value: 'CoA issued on site + Full post-operation narrative report' },
    ],
    contact: {
      name: 'Capt. Richard Pendelton',
      role: 'Director of Marine Warranty · AqualisBraemar LOC',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      email: 'mws.operations@aqualisbraemar.com',
      phone: '+61 8 9226 2200',
    },
  },
];
