/* 
  file summary: centralized mock dataset for service provider marketplace offerings (vessels, equipment, crew, services).
  responsibilities: provides verified third-party maritime assets and service offerings for chartering, leasing, and engagement.
  role in system: loaded by marketplaceHelpers.ts and useMapStore.ts.
*/

import { MarketplaceItem } from '../types/marketplace';

export const MOCK_MARKETPLACE_ITEMS: MarketplaceItem[] = [
  // 1. Service Provider Vessels
  {
    id: 'MAP-VES-2026-MKT-00008',
    name: 'MV Meridian Pioneer',
    category: 'vessel',
    subcategory: 'PSV / Multipurpose',
    providerOrg: 'Meridian Marine Services Pty Ltd',
    location: 'Darwin, NT',
    availabilityStatus: 'Available for Charter',
    availabilityTagColor: '#059669',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1661879449050-069f67e200bd?q=80&w=1122&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    shortDescription: 'High-capacity DP2 platform supply vessel fitted for bulk mud, deck cargo, and offshore support.',
    metrics: [
      { label: 'Capacity (DWT)', value: '4,200 MT' },
      { label: 'Assurance / Class', value: 'DNV · 70% Ready' },
    ],
    complianceReadinessScore: 70,
    rateEstimate: 'AUD 28,500 / day',
    mobilizationLeadTime: '48 Hours',
    certifications: ['DNV +100A1 DP2', 'AMSA Statutory Pack', 'SOLAS / ISPS Fully Certified'],
    operationalCapabilities: [
      'Deck cargo area 850 m2 with 10t/m2 loading strength',
      'Dynamic Positioning DP2 (Kongsberg K-Pos 22)',
      'Dual fuel low-sulphur compliant propulsion (2x 2,600 kW)',
      'Liquid mud and dry bulk pneumatic discharge systems',
    ],
    detailedSpecs: [
      { label: 'IMO Number', value: '9845120' },
      { label: 'Classification', value: 'DNV +100A1 PSV DP2' },
      { label: 'Year Built', value: '2022 (Vard Marine Norway)' },
      { label: 'Length Overall (LOA)', value: '84.5 m' },
      { label: 'Beam / Draft', value: '19.0 m / 5.9 m' },
      { label: 'Gross Tonnage', value: '3,400 GT' },
      { label: 'Deadweight Tonnage', value: '4,200 MT' },
      { label: 'Clear Deck Area', value: '850 m2' },
      { label: 'DP Capability', value: 'DP Class 2 (Kongsberg)' },
      { label: 'Accommodation', value: '32 Berths (Fully Air-Conditioned)' },
    ],
    contact: {
      name: 'Jonathan Briggs',
      role: 'Fleet Commercial Director · Meridian Marine',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      email: 'chartering@meridianmarine.com.au',
      phone: '+61 8 8981 4455',
    },
    linkedEntityId: 'VESSEL-008',
    linkedEntityType: 'vessel',
    photos: [
      'https://plus.unsplash.com/premium_photo-1661879449050-069f67e200bd?q=80&w=1122&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    id: 'MAP-VES-2026-MKT-00009',
    name: 'MV Austral Horizon',
    category: 'vessel',
    subcategory: 'PSV / Deck & Liquid Cargo',
    providerOrg: 'Austral Ocean Shipping Ltd',
    location: 'Fremantle, WA',
    availabilityStatus: 'Available for Charter',
    availabilityTagColor: '#059669',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1661962278758-d529030366fb?q=80&w=1228&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    shortDescription: 'Modern offshore supply vessel with advanced liquid mud management and dual bow thrusters.',
    metrics: [
      { label: 'Capacity (DWT)', value: '4,800 MT' },
      { label: 'Assurance / Class', value: "Lloyd's Register · 100% Ready" },
    ],
    complianceReadinessScore: 100,
    rateEstimate: 'AUD 31,000 / day',
    mobilizationLeadTime: '24 Hours',
    certifications: ["Lloyd's Register +100A1", 'IOPP Tier III Compliant', 'AMSA Safety Construction'],
    operationalCapabilities: [
      'Large clear deck area 920 m2 with heavy container fittings',
      'Converteam Dynamic Positioning DP2 Suite',
      'Automated tank washing and toxic vapor recovery',
      'Full FiFi 1 firefighting water spray monitors',
    ],
    detailedSpecs: [
      { label: 'IMO Number', value: '9782143' },
      { label: 'Classification', value: "Lloyd's Register +100A1 DP2" },
      { label: 'Year Built', value: '2021 (Damen Shipyards)' },
      { label: 'Length Overall (LOA)', value: '89.2 m' },
      { label: 'Beam / Draft', value: '20.0 m / 6.2 m' },
      { label: 'Gross Tonnage', value: '4,100 GT' },
      { label: 'Deadweight Tonnage', value: '4,800 MT' },
      { label: 'Deck Load Capacity', value: '2,200 MT' },
      { label: 'DP Capability', value: 'DP Class 2 (Converteam)' },
      { label: 'Accommodation', value: '28 Berths' },
    ],
    contact: {
      name: 'Elena Rostova',
      role: 'Commercial Operations Lead · Austral Ocean',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
      email: 'charter@australocean.com.au',
      phone: '+61 8 9335 8820',
    },
    linkedEntityId: 'VESSEL-009',
    linkedEntityType: 'vessel',
    photos: [
      'https://plus.unsplash.com/premium_photo-1661962278758-d529030366fb?q=80&w=1228&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      'https://images.unsplash.com/photo-1505705694340-019e1e335916?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    id: 'MAP-VES-2026-MKT-00010',
    name: 'MV Oceanic Sentinel',
    category: 'vessel',
    subcategory: 'AHTS / Towing',
    providerOrg: 'Oceanic Horizon Logistics Pty Ltd',
    location: 'Dampier, WA',
    availabilityStatus: 'Available for Charter',
    availabilityTagColor: '#059669',
    imageUrl: 'https://plus.unsplash.com/premium_photo-1664298003939-e93f37196118?q=80&w=1333&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    shortDescription: 'Anchor handling tug supply vessel with 180T continuous bollard pull for rig moves.',
    metrics: [
      { label: 'Bollard Pull', value: '180 MT' },
      { label: 'Assurance / Class', value: 'ABS · 100% Ready' },
    ],
    complianceReadinessScore: 100,
    rateEstimate: 'AUD 34,500 / day',
    mobilizationLeadTime: '72 Hours',
    certifications: ['ABS +A1 AHTS DP2', 'IMCA Rig Move Vetted', 'SOLAS / ISPS Certified'],
    operationalCapabilities: [
      'Continuous bollard pull 180 MT with 400T brake anchor handling winch',
      'Kongsberg K-Pos DP2 integrated joystick system',
      'Hydraulic shark jaws and towing pins (350T SWL)',
      'Heavy offshore anchor recovery and rig repositioning',
    ],
    detailedSpecs: [
      { label: 'IMO Number', value: '9651892' },
      { label: 'Classification', value: 'ABS +A1 Offshore Support Vessel (AHTS) DP2' },
      { label: 'Year Built', value: '2020 (Keppel FELS)' },
      { label: 'Length Overall (LOA)', value: '82.0 m' },
      { label: 'Beam / Draft', value: '18.5 m / 5.7 m' },
      { label: 'Gross Tonnage', value: '3,300 GT' },
      { label: 'Bollard Pull', value: '180 MT Continuous' },
      { label: 'Towing Winch', value: 'Brattvaag Double Drum 400T' },
      { label: 'DP Capability', value: 'DP Class 2 (Kongsberg K-Pos)' },
      { label: 'Accommodation', value: '30 Berths' },
    ],
    contact: {
      name: 'Justin Franci',
      role: 'Senior Marine Broker · Oceanic Horizon',
      avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80',
      email: 'brokerage@oceanichorizon.com.au',
      phone: '+61 8 9183 9900',
    },
    linkedEntityId: 'VESSEL-010',
    linkedEntityType: 'vessel',
    photos: [
      'https://plus.unsplash.com/premium_photo-1664298003939-e93f37196118?q=80&w=1333&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1000&q=80',
    ],
  },

  // 2. Service Provider Equipment
  {
    id: 'MAP-EQP-2026-MKT-00101',
    name: 'Schilling HD 150HP Work-Class ROV System',
    category: 'equipment',
    subcategory: 'Subsea Robotics & Intervention',
    providerOrg: 'Subsea 7 Engineering & Robotics',
    location: 'Dampier Shorebase, WA',
    availabilityStatus: 'Mobilization Ready',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?auto=format&fit=crop&w=1000&q=80',
    shortDescription: 'Deepwater heavy work-class ROV spread with 3,000m depth rating and dual manipulator arms.',
    metrics: [
      { label: 'Depth Rating', value: '3,000 MSW' },
      { label: 'Power / Payload', value: '150 HP · 250 kg' },
    ],
    complianceReadinessScore: null,
    rateEstimate: 'AUD 8,200 / day spread',
    mobilizationLeadTime: '3 Days',
    certifications: ['IMCA R004 Compliant', 'DNV Lifting Appliance Survey', 'ISO 13628-8 Subsea Standard'],
    operationalCapabilities: [
      'Dual 7-function Schilling Titan 4 spatial manipulator arms',
      'Dedicated Top-Hat TMS (Tether Management System) with 800m tether',
      'High-definition multibeam imaging sonar and HD digital video cameras',
      'Hydraulic torque tool, hot stabs, and cutter tool spreads included',
    ],
    detailedSpecs: [
      { label: 'System Type', value: 'Heavy Work-Class Hydraulic ROV' },
      { label: 'Depth Rating', value: '3,000 meters sea water (MSW)' },
      { label: 'Hydraulic Power Unit', value: '150 HP (112 kW) Curvetech' },
      { label: 'Payload Capacity', value: '250 kg in air' },
      { label: 'Tether Length', value: '800 m excursion from TMS' },
      { label: 'Control Van', value: 'DNV 2.7-1 Zone 2 Certified Control Container' },
      { label: 'LARS Winch', value: 'Active Heave Compensated A-Frame Winch' },
      { label: 'Inspection Tooling', value: 'Class 1-4 Torque Tool, CP Probe, Laser Scaler' },
    ],
    contact: {
      name: 'Dr. Alistair MacIntyre',
      role: 'Subsea Operations Manager · Subsea 7',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
      email: 'subsea.tooling@subsea7.com',
      phone: '+61 8 9485 7100',
    },
    photos: [
      'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    id: 'MAP-EQP-2026-MKT-00102',
    name: 'Liebherr RL-K 4200 150T Active Heave Offshore Crane',
    category: 'equipment',
    subcategory: 'Machinery & Heavy Lifting',
    providerOrg: 'Boskalis Heavy Marine Transport',
    location: 'Henderson Facility, WA',
    availabilityStatus: 'Available for Lease',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1000&q=80',
    shortDescription: 'Pedestal-mounted knuckle boom crane with active heave compensation for subsea construction.',
    metrics: [
      { label: 'Max Capacity', value: '150 MT SWL' },
      { label: 'Boom Outreach', value: '45.0 Meters' },
    ],
    complianceReadinessScore: null,
    rateEstimate: 'AUD 12,000 / day',
    mobilizationLeadTime: '5 Days',
    certifications: ['DNVGL-ST-0378 Lifting Appliances', 'EN 13852-1 Offshore Cranes', 'AMSA Class Surveyed'],
    operationalCapabilities: [
      'Active Heave Compensation (AHC) down to 2,500m subsea water depth',
      'Knuckle boom design for minimal pendulum motion on heavy offshore decks',
      'Integrated auxiliary whip hoist with 20 MT SWL at 52m reach',
      'Fail-safe overload protection and real-time boom angle monitoring',
    ],
    detailedSpecs: [
      { label: 'Manufacturer', value: 'Liebherr Offshore Cranes' },
      { label: 'Model', value: 'RL-K 4200 Heavy Construction' },
      { label: 'Main Hoist SWL', value: '150 MT @ 14 m radius' },
      { label: 'Max Radius SWL', value: '35 MT @ 45 m radius' },
      { label: 'Subsea Wire Capacity', value: '2,500 m non-rotating wire rope' },
      { label: 'Heave Compensation', value: 'Active Electro-Hydraulic (AHC)' },
      { label: 'Pedestal Diameter', value: '3.8 m standard flange' },
      { label: 'Power Consumption', value: '3x 350 kW integrated power pack' },
    ],
    contact: {
      name: 'Willem Van Dijk',
      role: 'Heavy Lifting Asset Manager · Boskalis',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      email: 'cranes@boskalis.com.au',
      phone: '+61 8 9437 2200',
    },
    photos: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1000&q=80',
    ],
  },
  {
    id: 'MAP-EQP-2026-MKT-00103',
    name: 'Kongsberg K-Pos DP-22 Dual Redundant DP Unit',
    category: 'equipment',
    subcategory: 'Navigation & Bridge Systems',
    providerOrg: 'Kongsberg Maritime Services',
    location: 'Perth Tech Depot, WA',
    availabilityStatus: 'In Stock / Ready',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1000&q=80',
    shortDescription: 'Complete standalone DP2 operator station and dual controller cabinet with DGPS sensors.',
    metrics: [
      { label: 'Redundancy', value: 'Dual Class 2' },
      { label: 'Compliance', value: 'IMO Class II / DP2' },
    ],
    complianceReadinessScore: null,
    rateEstimate: 'AUD 3,500 / day (Lease)',
    mobilizationLeadTime: '24 Hours',
    certifications: ['DNV Class Notation DP-2', 'ABS Class 2 Certified', 'IMO MSC/Circ.645 Guideline'],
    operationalCapabilities: [
      'Dual controller architecture with bumpless transfer on fault detection',
      'Integrated CyScan laser and HiPAP 502 acoustic positioning inputs',
      'Dual multi-constellation Fugro Marinestar GNSS receivers',
      'Standardized interface for Rolls-Royce, Wärtsilä, and Schottel thrusters',
    ],
    detailedSpecs: [
      { label: 'System Series', value: 'Kongsberg K-Pos Generation 7' },
      { label: 'Hardware Architecture', value: 'Dual Redundant VME Controllers' },
      { label: 'Operator Stations', value: '2x 24-inch TFT Touch Consoles' },
      { label: 'Reference Inputs', value: '2x DGPS, 1x Laser, 1x Acoustic, 3x MRU' },
      { label: 'Wind Sensors', value: '3x Ultrasonic Wind Sensors with De-Icing' },
      { label: 'Power Supply', value: 'Dual 24V DC / 230V AC UPS Buffered' },
    ],
    contact: {
      name: 'Kari Lindqvist',
      role: 'Maritime Systems Engineer · Kongsberg',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
      email: 'support.dp@kongsberg.com',
      phone: '+61 8 9486 0100',
    },
    photos: [
      'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1000&q=80',
    ],
  },

  // 3. Specialized Service Provider Crew
  {
    id: 'MAP-CRW-2026-MKT-00201',
    name: 'Capt. Callum Sterling',
    category: 'crew',
    subcategory: 'Master Mariner / DP Class 3 Unlimited',
    providerOrg: 'Atlas Professionals Marine Crewing',
    location: 'Perth, WA (Available Worldwide)',
    availabilityStatus: 'Available Immediately',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
    shortDescription: 'Senior Master Mariner with 16 years command experience on large AHTS, construction vessels, and FPSO offloading.',
    metrics: [
      { label: 'Rank / Grade', value: 'Master Unlimited' },
      { label: 'STCW Validity', value: 'Valid to 2031' },
    ],
    complianceReadinessScore: null,
    rateEstimate: 'Day Rate on Application',
    mobilizationLeadTime: '24 Hours',
    certifications: ['Master Mariner (STCW II/2)', 'Nautical Institute DP Unlimited', 'BOSIET / OPITO Offshore Safety', 'BHP / Chevron Marine Inducted'],
    operationalCapabilities: [
      'Over 4,500 logged hours on DP2 / DP3 construction and anchor handling operations',
      'Extensive FPSO offloading, tandem mooring, and heavy subsea installation experience',
      'Advanced ship-handling instructor for dynamic positioning simulation centers',
      'Full Australian AMSA and UK MCA Certificate of Competency (CoC)',
    ],
    detailedSpecs: [
      { label: 'Nationality', value: 'Australian' },
      { label: 'Seamans Book', value: 'AMSA SB-AU-448102' },
      { label: 'Medical Clearance', value: 'AMSA Marine Medical (Valid to 2028)' },
      { label: 'DP Certificate No.', value: 'NI-DP-UNL-99214' },
      { label: 'Total Sea Service', value: '16 Years (11 Years in Command)' },
      { label: 'Primary Vessel Types', value: 'AHTS, PSV, SSV, Cable Layer' },
    ],
    contact: {
      name: 'Sarah O’Reilly',
      role: 'Senior Marine Crewing Manager · Atlas Professionals',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
      email: 'crewing.wa@atlasprofessionals.com.au',
      phone: '+61 8 9214 7700',
    },
    photos: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'MAP-CRW-2026-MKT-00202',
    name: 'Henrik Vestergaard',
    category: 'crew',
    subcategory: 'Chief Engineer / High-Voltage & Dual-Fuel Specialist',
    providerOrg: 'Brunel International Marine Staffing',
    location: 'Fremantle, WA',
    availabilityStatus: 'Available Next Week',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=800&q=80',
    shortDescription: 'Chief Engineer specializing in diesel-electric dual-fuel propulsion, closed-bus DP3 power management, and thrusters.',
    metrics: [
      { label: 'Rank / Grade', value: 'Chief Engineer (III/2)' },
      { label: 'STCW Validity', value: 'Valid to 2030' },
    ],
    complianceReadinessScore: null,
    rateEstimate: 'Standard Tier Rate',
    mobilizationLeadTime: '48 Hours',
    certifications: ['STCW III/2 Chief Engineer Unlimited', 'High Voltage Safety (6.6 kV / 11 kV)', 'Wärtsilä & Rolls-Royce Certified', 'OPITO HUET / CA-EBS'],
    operationalCapabilities: [
      'Over 14 years managing complex diesel-electric automation and thruster maintenance',
      'Expert in closed-bus DP power management system troubleshooting and FMEA verification',
      'Advanced drydocking engineering lead for multi-engine complete overhauls',
      'Fluent in computerized maintenance management systems (AMOS, StarIPS)',
    ],
    detailedSpecs: [
      { label: 'Nationality', value: 'Danish (Australian PR)' },
      { label: 'Seamans Book', value: 'DK-SB-88201 / AMSA Endorsed' },
      { label: 'Medical Clearance', value: 'OGUK & AMSA Medical Valid' },
      { label: 'Power Systems', value: '6.6 kV High Voltage Diesel-Electric' },
      { label: 'Total Sea Service', value: '14 Years' },
      { label: 'Primary Vessel Types', value: 'DP3 SSV, Pipelay, Drillships' },
    ],
    contact: {
      name: 'Mark Jansen',
      role: 'Offshore Technical Recruiter · Brunel Marine',
      avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80',
      email: 'marine.perth@brunel.net',
      phone: '+61 8 9429 5600',
    },
    photos: [
      'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'MAP-CRW-2026-MKT-00203',
    name: 'Capt. Elena Rostova',
    category: 'crew',
    subcategory: 'Senior Dynamic Positioning Operator (DPO) / Chief Officer',
    providerOrg: 'Southern Marine Personnel Ltd',
    location: 'Darwin, NT',
    availabilityStatus: 'Available for Mobilization',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=800&q=80',
    shortDescription: 'Senior DP Operator with 3,800+ logged DP hours on subsea construction, diving support, and seabed intervention vessels.',
    metrics: [
      { label: 'Rank / Grade', value: 'Chief Officer / DPO' },
      { label: 'DP Experience', value: '3,800+ Hours' },
    ],
    complianceReadinessScore: null,
    rateEstimate: 'Standard Day Rate',
    mobilizationLeadTime: '24 Hours',
    certifications: ['Chief Mate Unlimited (STCW II/2)', 'Nautical Institute DP Unlimited', 'IMCA DP Log Book Validated', 'OPITO BOSIET with CA-EBS'],
    operationalCapabilities: [
      'Expertise in Kongsberg K-Pos Generation 7 and Converteam DP control consoles',
      'Over 8 years supporting saturation diving operations within 500m platform safety zones',
      'Certified ECDIS instructor with advanced passage planning & risk assessment competencies',
      'Thorough experience in CyScan, Artemis, and HiPAP acoustic reference sensor calibration',
    ],
    detailedSpecs: [
      { label: 'Nationality', value: 'Australian' },
      { label: 'Seamans Book', value: 'AMSA SB-AU-519280' },
      { label: 'Medical Clearance', value: 'AMSA & OGUK Marine Medical (Valid 2028)' },
      { label: 'DP Console Types', value: 'Kongsberg K-Pos 21/22/32, Converteam' },
      { label: 'Total Sea Service', value: '11 Years (6 Years Senior DPO)' },
      { label: 'Primary Vessel Types', value: 'DSV, Construction OSV, Well Intervention' },
    ],
    contact: {
      name: 'Marcus Chen',
      role: 'Crewing Director · Southern Marine Personnel',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      email: 'placements@southernmarine.com.au',
      phone: '+61 8 8944 1200',
    },
    photos: [
      'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'MAP-CRW-2026-MKT-00204',
    name: 'Dr. Arthur Vance',
    category: 'crew',
    subcategory: 'Saturation Dive Superintendent & Life Support Director',
    providerOrg: 'Subsea 7 Engineering & Robotics',
    location: 'Dampier Shorebase, WA',
    availabilityStatus: 'Available on Call',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=800&q=80',
    shortDescription: 'IMCA Class A Saturation Diving Superintendent with 20+ years managing deep saturation spreads and hyperbaric rescue.',
    metrics: [
      { label: 'Specialization', value: 'Saturation Diving' },
      { label: 'Accreditation', value: 'IMCA Life Support Dir' },
    ],
    complianceReadinessScore: null,
    rateEstimate: 'Consultant / Lead Rate',
    mobilizationLeadTime: '48 Hours',
    certifications: ['IMCA Saturation Dive Superintendent', 'IMCA Life Support Director', 'Hyperbaric Chamber Safety Cert', 'DMAC Medical Supervisor'],
    operationalCapabilities: [
      'Supervision of 12-man 300m saturation diving system with dual bell deployment',
      'Deep subsea pipeline tie-in, spool piece metrology, and hot-tap weld oversight',
      'Hyperbaric evacuation system (HRV/HRU) commissioning and emergency drills lead',
      'Comprehensive IMCA D014, D023, and D024 diving audit lead surveyor',
    ],
    detailedSpecs: [
      { label: 'Nationality', value: 'British (Australian Resident)' },
      { label: 'Certification Body', value: 'IMCA International' },
      { label: 'Max Working Depth', value: '300 MSW (Metres Sea Water)' },
      { label: 'Medical Clearance', value: 'Diving Medical Advisory Committee (DMAC) Cleared' },
      { label: 'Industry Experience', value: '22 Years Subsea & Diving Operations' },
      { label: 'Key Projects', value: 'Gorgon, Ichthys, Scarborough Gas Spreads' },
    ],
    contact: {
      name: 'Jonathan Briggs',
      role: 'Subsea Operations Director · Subsea 7',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      email: 'diving.leads@subsea7.com.au',
      phone: '+61 8 9485 7150',
    },
    photos: [
      'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'MAP-CRW-2026-MKT-00205',
    name: 'Liam Gallagher',
    category: 'crew',
    subcategory: 'Senior Work-Class ROV Pilot Technician & Tooling Lead',
    providerOrg: 'Oceaneering Marine Subsea Staffing',
    location: 'Broome, WA',
    availabilityStatus: 'Available Immediately',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
    shortDescription: 'Senior ROV Pilot Technician with 4,200+ logged hours operating Schilling HD and Millennium work-class ROV spreads.',
    metrics: [
      { label: 'Specialization', value: 'Work-Class ROV' },
      { label: 'Flight Hours', value: '4,200+ Logged' },
    ],
    complianceReadinessScore: null,
    rateEstimate: 'Tier 1 Pilot Rate',
    mobilizationLeadTime: '24 Hours',
    certifications: ['IMCA R002 / R004 Senior Pilot Technician', 'High Voltage ROV Power Safety', 'Titan 4 Manipulator Specialist', 'OPITO BOSIET CA-EBS'],
    operationalCapabilities: [
      'Dual 7-function hydraulic spatial manipulator dexterity for subsea valve operations',
      'Subsea CP profiling, cathodic survey, multibeam sonar bathymetry piloting',
      'Fibre optic telemetry diagnostic and high-voltage umbilical repair in field',
      'Overboard LARS A-frame handling and TMS deployment in sea state 5+',
    ],
    detailedSpecs: [
      { label: 'Nationality', value: 'Australian' },
      { label: 'ROV System Expertise', value: 'Schilling HD/UHD, Oceaneering Millennium/Maxx' },
      { label: 'Subsea Depth Record', value: '2,850 MSW' },
      { label: 'Electronics & Hydraulics', value: 'Trade Certified Mechatronics / Fluid Power' },
      { label: 'Total Sea Service', value: '9 Years Offshore ROV Pilot' },
      { label: 'Inductions', value: 'Woodside, Chevron, Shell Prelude FLNG' },
    ],
    contact: {
      name: 'Claire Thornton',
      role: 'Robotics Personnel Lead · Oceaneering',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
      email: 'rov.crewing@oceaneering.com',
      phone: '+61 8 9193 4500',
    },
    photos: [
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'MAP-CRW-2026-MKT-00206',
    name: 'Capt. Tane Mahuta',
    category: 'crew',
    subcategory: 'Lead Towing Master & Deepwater Mooring Specialist',
    providerOrg: 'Pacific Offshore Maritime Personnel',
    location: 'Henderson Facility, WA',
    availabilityStatus: 'Available for Campaign',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=800&q=80',
    shortDescription: 'Towing Master with 85+ successful deepwater rig moves, FPSO disconnects, and pre-laid mooring spread installations.',
    metrics: [
      { label: 'Specialization', value: 'Towing Master' },
      { label: 'Rig Moves', value: '85+ Completed' },
    ],
    complianceReadinessScore: null,
    rateEstimate: 'Campaign Lump Sum / Day Rate',
    mobilizationLeadTime: '48 Hours',
    certifications: ['Master Unlimited (STCW II/2)', 'SOMWS Rig Move Master Approved', 'Anchor Handling & Heavy Towing Lead', 'AMSA Pilotage Exemption (NWS)'],
    operationalCapabilities: [
      'Multi-tug ocean tow management for semisubmersibles and heavy transport barges',
      'Design and live execution of 8-point and 12-point synthetic & chain mooring arrays',
      'Detailed catenary calculations, bollard pull verification, and emergency abort plans',
      'Onboard bridge advisory and lead pilotage for complex port and field entries',
    ],
    detailedSpecs: [
      { label: 'Nationality', value: 'New Zealander (Australian Resident)' },
      { label: 'Seamans Book', value: 'NZ-SB-77412 / AMSA Endorsed' },
      { label: 'Medical Clearance', value: 'AMSA & OGUK Marine Medical' },
      { label: 'Total Sea Service', value: '24 Years (14 Years Towing Master)' },
      { label: 'Max Rig Displacement Handled', value: '55,000 MT Semi-Submersible' },
      { label: 'Regional Experience', value: 'North West Shelf, Bass Strait, Timor Sea' },
    ],
    contact: {
      name: 'Justin Franci',
      role: 'Offshore Personnel Director · Pacific Offshore',
      avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80',
      email: 'marine.crew@pacificoffshore.com.au',
      phone: '+61 8 9431 8900',
    },
    photos: [
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1528892952291-009c663ce843?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'MAP-CRW-2026-MKT-00207',
    name: 'Sarah Jenkins',
    category: 'crew',
    subcategory: 'Senior Marine QHSE & Environmental Compliance Officer',
    providerOrg: 'Global Maritime Assurance Group',
    location: 'Perth, WA',
    availabilityStatus: 'Available Immediately',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80',
    shortDescription: 'Marine Environmental Lead with deep expertise in MARPOL Annex VI decarbonization, NOPSEMA safety cases, and IMCA audits.',
    metrics: [
      { label: 'Specialization', value: 'QHSE Lead Auditor' },
      { label: 'Accreditation', value: 'ISO 14001 / 45001' },
    ],
    complianceReadinessScore: null,
    rateEstimate: 'Standard Day Rate',
    mobilizationLeadTime: '24 Hours',
    certifications: ['Lead Auditor ISO 9001 / 14001 / 45001', 'NEBOSH International Diploma in OHS', 'IMCA e-CMID Accredited Vessel Inspector', 'NOPSEMA Environmental Auditor'],
    operationalCapabilities: [
      'Comprehensive vessel environmental baseline audits & greenhouse gas monitoring',
      'Offshore vessel safety case bridging document development and class submission',
      'Major accident event (MAE) risk workshops, HAZID, and HAZOP chairing',
      'Ballast water management and biofouling risk assessment for Australian waters',
    ],
    detailedSpecs: [
      { label: 'Nationality', value: 'Australian' },
      { label: 'Professional Degree', value: 'B.Sc. Marine Environmental Science (Curtin Univ)' },
      { label: 'Medical Clearance', value: 'OGUK Offshore Medical Cleared' },
      { label: 'Industry Experience', value: '13 Years Offshore Oil & Gas / Renewables' },
      { label: 'Audit Registrations', value: 'IRCA Certified Lead Auditor #99412' },
      { label: 'Primary Deployments', value: 'FPSO, Heavy Lift Crane Vessels, Dredgers' },
    ],
    contact: {
      name: 'David Sutherland',
      role: 'Principal Assurance Director · Global Maritime',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      email: 'qhse.crewing@globalmaritime.com',
      phone: '+61 8 9268 4050',
    },
    photos: [
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: 'MAP-CRW-2026-MKT-00208',
    name: 'Marcus Vance-Chen',
    category: 'crew',
    subcategory: 'Offshore Heavy Lift & Deck Superintendent',
    providerOrg: 'Boskalis Heavy Marine Transport',
    location: 'Fremantle, WA',
    availabilityStatus: 'Available Next Week',
    availabilityTagColor: '#059669',
    imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=800&q=80',
    shortDescription: 'Deck Superintendent specializing in active heave crane operations, subsea manifold deployment, and deck seafastening.',
    metrics: [
      { label: 'Specialization', value: 'Heavy Lift & Deck' },
      { label: 'Crane Lifts', value: 'Up to 4,000 MT SWL' },
    ],
    complianceReadinessScore: null,
    rateEstimate: 'Superintendent Tier Rate',
    mobilizationLeadTime: '48 Hours',
    certifications: ['LEEA Certified Lifting Inspector', 'OPITO Rigging & Lifting Stage 4 Assessor', 'IMCA Deck Safety Supervisor', 'BOSIET with EBS Valid'],
    operationalCapabilities: [
      'Supervision of complex dual-crane tandem subsea lifting operations in active swell',
      'Seafastening fabrication, weld inspection, and loadout calculation validation',
      'Comprehensive deck crew management, toolbox talk leadership, and lift plan signoff',
      'Subsea wet-parking and guide-wire deployment for template installations',
    ],
    detailedSpecs: [
      { label: 'Nationality', value: 'Australian' },
      { label: 'Seamans Book', value: 'AMSA SB-AU-339102' },
      { label: 'Medical Clearance', value: 'AMSA & OGUK Marine Medical' },
      { label: 'Trade Qualification', value: 'Master Rigger / Structural Fabricator' },
      { label: 'Total Sea Service', value: '15 Years Offshore Construction' },
      { label: 'Major Installations Handled', value: 'Subsea Manifolds, PLEMs, Suction Piles' },
    ],
    contact: {
      name: 'Willem Van Dijk',
      role: 'Heavy Marine Asset Manager · Boskalis',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      email: 'deck.superintendents@boskalis.com.au',
      phone: '+61 8 9437 2220',
    },
    photos: [
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
    ],
  },
];

