/*
  file summary: mock project charter data with cross-org asset links and master assurance rollup.
  responsibilities: seeds sample Northwind dangerous-route project with vessel + crew assurance sets.
  role in system: loaded by useMapStore on initialization.
*/

import { AssuranceSet } from '../types/assurance';
import { Project } from '../types/project';

export const PROJECT_SEED_ASSURANCE_SETS: AssuranceSet[] = [
  {
    id: 'AS-01-V001',
    title: 'MV Pacific Endeavour — Vessel Charter Vetting',
    assuranceType: 'Vessel',
    subtypes: ['Vessel'],
    vesselId: 'VESSEL-001',
    vesselName: 'MV Pacific Endeavour',
    imoNumber: '9123456',
    initiatorOrg: 'Northwind Marine Pty Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterer: 'Northwind Marine Pty Ltd',
    charterWindowStart: '2026-11-01',
    charterWindowEnd: '2027-02-28',
    stage: 'Verification',
    readinessScore: 78,
    mandatoryInspectionRequired: true,
    inspectionCompleted: false,
    requirements: [
      {
        id: 'REQ-V001-1',
        subtype: 'Vessel',
        category: 'Statutory Certificate',
        title: 'Cert1 — Certificate of Class',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 98,
        verifierStatus: 'Verified',
      },
      {
        id: 'REQ-V001-2',
        subtype: 'Vessel',
        category: 'Statutory Certificate',
        title: 'Cert2 — Cargo Ship Safety Equipment',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 96,
        verifierStatus: 'Verified',
      },
      {
        id: 'REQ-V001-3',
        subtype: 'Vessel',
        category: 'Environmental Certificate',
        title: 'Cert3 — IOPP Certificate Annex I',
        isMandatory: true,
        isFulfilled: false,
        ocrConfidence: 0,
        verifierStatus: 'Pending',
      },
    ],
    createdByPersona: 'Administrator',
  },
  {
    id: 'AS-01-C001',
    title: 'Capt. Alexander Wright — Crew Charter Vetting',
    assuranceType: 'Crew',
    subtypes: ['Crew'],
    vesselId: 'VESSEL-001',
    vesselName: 'MV Pacific Endeavour',
    imoNumber: '9123456',
    crewId: 'CREW-101',
    crewName: 'Capt. Alexander Wright',
    initiatorOrg: 'Northwind Marine Pty Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterer: 'Northwind Marine Pty Ltd',
    charterWindowStart: '2026-11-01',
    charterWindowEnd: '2027-02-28',
    stage: 'Certified',
    clientWorkflowStage: 'approved',
    approverDecision: 'Approved',
    readinessScore: 92,
    mandatoryInspectionRequired: false,
    inspectionCompleted: false,
    requirements: [
      {
        id: 'REQ-C001-1',
        subtype: 'Crew',
        category: 'Crew Credential',
        title: 'CrewCert1 — STCW Master CoC Endorsement',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 99,
        verifierStatus: 'Verified',
      },
      {
        id: 'REQ-C001-2',
        subtype: 'Crew',
        category: 'Medical Fitness Certificate',
        title: 'CrewCert2 — ENG1 Medical Fitness',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 97,
        verifierStatus: 'Verified',
      },
    ],
    createdByPersona: 'Administrator',
  },
  {
    id: 'AS-02-C002-1',
    title: 'Armed Security Team — Project Charter Vetting',
    assuranceType: 'Crew',
    subtypes: ['Crew'],
    vesselId: 'VESSEL-001',
    vesselName: 'MV Pacific Endeavour',
    imoNumber: '9123456',
    crewId: 'CREW-104',
    crewName: 'Bosun David Kowalski',
    initiatorOrg: 'Gulf Security Services Pty Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterer: 'Northwind Marine Pty Ltd',
    charterWindowStart: '2026-11-01',
    charterWindowEnd: '2027-02-28',
    stage: 'Initiated',
    readinessScore: 45,
    mandatoryInspectionRequired: false,
    inspectionCompleted: false,
    requirements: [
      {
        id: 'REQ-C002-1',
        subtype: 'Crew',
        category: 'Crew Custom Requirement',
        title: 'Armed Guard License & Firearms Endorsement',
        isMandatory: true,
        isFulfilled: false,
        ocrConfidence: 0,
        verifierStatus: 'Pending',
      },
    ],
    createdByPersona: 'Administrator',
  },
  {
    id: 'AS-02-P001',
    title: 'Northwind Dangerous Route Transit — Project Master Assurance',
    assuranceType: 'Project',
    subtypes: ['Vessel', 'Crew', 'Activity', 'Equipment'],
    projectId: 'MAP-PROJ-2026-MARINE-007',
    projectName: 'Northwind Dangerous Route Transit',
    vesselId: 'VESSEL-001',
    vesselName: 'MV Pacific Endeavour',
    imoNumber: '9123456',
    initiatorOrg: 'Northwind Marine Pty Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterer: 'Northwind Marine Pty Ltd',
    charterWindowStart: '2026-11-01',
    charterWindowEnd: '2027-02-28',
    stage: 'Verification',
    readinessScore: 45,
    mandatoryInspectionRequired: true,
    inspectionCompleted: false,
    isProjectMaster: true,
    parentProjectId: 'MAP-PROJ-2026-MARINE-007',
    aggregatedFromSetIds: ['AS-01-V001', 'AS-01-C001'],
    requirements: [
      {
        id: 'PROJ-LINK-AS-01-V001',
        subtype: 'Vessel',
        category: 'Custom Requirement',
        title: 'MV Pacific Endeavour — Vessel Charter Vetting',
        description: 'Linked sub-set for MV Pacific Endeavour (Vessel) · Northwind Marine Pty Ltd',
        fulfillmentType: 'assurance_set',
        linkedAssuranceSetId: 'AS-01-V001',
        isMandatory: true,
        isFulfilled: false,
        ocrConfidence: 0,
        verifierStatus: 'Pending',
      },
      {
        id: 'PROJ-LINK-AS-01-C001',
        subtype: 'Crew',
        category: 'Custom Requirement',
        title: 'Capt. Alexander Wright — Crew Charter Vetting',
        description: 'Linked sub-set for Capt. Alexander Wright (Crew) · Northwind Marine Pty Ltd',
        fulfillmentType: 'assurance_set',
        linkedAssuranceSetId: 'AS-01-C001',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 0,
        verifierStatus: 'Verified',
      },
    ],
    createdByPersona: 'Administrator',
  },
  {
    id: 'AS-02-P008-MASTER',
    title: 'Pacific Endeavour — Hull Fouling Removal — Project Master Assurance',
    assuranceType: 'Project',
    subtypes: ['Vessel', 'Crew', 'Activity', 'Equipment'],
    projectId: 'MAP-PROJ-2026-MARINE-008',
    projectName: 'Pacific Endeavour — Hull Fouling Removal',
    vesselId: 'VESSEL-001',
    vesselName: 'MV Pacific Endeavour',
    imoNumber: '9123456',
    initiatorOrg: 'Northwind Marine Pty Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterer: 'Northwind Marine Pty Ltd',
    charterWindowStart: '2026-03-10',
    charterWindowEnd: '2026-03-12',
    stage: 'Initiated',
    readinessScore: 0,
    mandatoryInspectionRequired: false,
    inspectionCompleted: false,
    isProjectMaster: true,
    parentProjectId: 'MAP-PROJ-2026-MARINE-008',
    aggregatedFromSetIds: ['AS-01-V001'],
    requirements: [
      {
        id: 'PROJ-LINK-AS-01-V001-HULL',
        subtype: 'Vessel',
        category: 'Custom Requirement',
        title: 'MV Pacific Endeavour — Vessel Charter Vetting',
        description: 'Linked sub-set for MV Pacific Endeavour (Vessel) · Northwind Marine Pty Ltd',
        fulfillmentType: 'assurance_set',
        linkedAssuranceSetId: 'AS-01-V001',
        isMandatory: true,
        isFulfilled: false,
        ocrConfidence: 0,
        verifierStatus: 'Pending',
      },
    ],
    createdByPersona: 'Administrator',
  },
  {
    id: 'AS-02-P009-MASTER',
    title: 'Southern Basin Platform Support Charter — Project Master Assurance',
    assuranceType: 'Project',
    subtypes: ['Vessel', 'Crew', 'Activity', 'Equipment'],
    projectId: 'MAP-PROJ-2026-MARINE-009',
    projectName: 'Southern Basin Platform Support Charter',
    vesselId: 'VESSEL-005',
    vesselName: 'MV Atlantic Ocean',
    imoNumber: '9712044',
    initiatorOrg: 'Southern Basin Energy Pty Ltd',
    initiatorRole: 'C Admin · Client Created',
    charterer: 'Southern Basin Energy Pty Ltd',
    clientOrg: 'Southern Basin Energy Pty Ltd',
    serviceProviderOrg: 'Northwind Marine Pty Ltd',
    charterWindowStart: '2026-09-15',
    charterWindowEnd: '2027-09-15',
    stage: 'Approval',
    readinessScore: 70,
    mandatoryInspectionRequired: true,
    inspectionCompleted: true,
    isProjectMaster: true,
    parentProjectId: 'MAP-PROJ-2026-MARINE-009',
    aggregatedFromSetIds: ['AS-2026-005'],
    clientWorkflowStage: 'in_review',
    sentForReviewAt: '2026-09-20T10:00:00Z',
    requirements: [
      {
        id: 'PROJ-LINK-AS-2026-005',
        subtype: 'Vessel',
        category: 'Custom Requirement',
        title: 'Southern Basin Platform Support Charter',
        description: 'Linked sub-set for MV Atlantic Ocean (Vessel) · Northwind Marine Pty Ltd',
        fulfillmentType: 'assurance_set',
        linkedAssuranceSetId: 'AS-2026-005',
        isMandatory: true,
        isFulfilled: false,
        ocrConfidence: 0,
        verifierStatus: 'Pending',
      },
    ],
    createdByPersona: 'C Admin',
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'MAP-PROJ-2026-MARINE-007',
    name: 'Northwind Dangerous Route Transit',
    projectType: 'Charter / Voyage',
    requestingOrganization: 'Northwind Marine Pty Ltd',
    clientOperator: 'Northwind Marine Pty Ltd',
    location: 'Timor Sea — High-Risk Transit Corridor',
    description: 'Multi-org charter composition for elevated-risk offshore transit with armed security detail.',
    charterer: 'Northwind Marine Pty Ltd',
    routeDescription: 'Dangerous route via Timor Passage — armed escort required for piracy-risk sector.',
    riskProfile: 'Armed Escort Required',
    charterWindowStart: '2026-11-01',
    charterWindowEnd: '2027-02-28',
    status: 'Assurance In Progress',
    operatorOrganization: 'Northwind Marine Pty Ltd',
    masterAssuranceSetId: 'AS-02-P001',
    readinessScore: 45,
    assetLinks: [
      {
        id: 'PAL-001',
        projectId: 'MAP-PROJ-2026-MARINE-007',
        assetType: 'Vessel',
        assetId: 'VESSEL-001',
        assetName: 'MV Pacific Endeavour',
        providerOrganization: 'Northwind Marine Pty Ltd',
        assuranceSetId: 'AS-01-V001',
        roleInProject: 'Subject vessel',
        addedAt: '2026-09-15T08:00:00Z',
        addedByPersona: 'Administrator',
      },
      {
        id: 'PAL-002',
        projectId: 'MAP-PROJ-2026-MARINE-007',
        assetType: 'Crew',
        assetId: 'CREW-101',
        assetName: 'Capt. Alexander Wright',
        providerOrganization: 'Northwind Marine Pty Ltd',
        assuranceSetId: 'AS-01-C001',
        roleInProject: 'Master / command crew',
        addedAt: '2026-09-15T08:05:00Z',
        addedByPersona: 'Administrator',
      },
    ],
  },
  {
    id: 'MAP-PROJ-2026-MARINE-008',
    name: 'Pacific Endeavour — Hull Fouling Removal',
    projectType: 'Service Engagement',
    requestingOrganization: 'Northwind Marine Pty Ltd',
    clientOperator: 'Northwind Marine Pty Ltd',
    location: 'Fremantle Inner Harbour — Berth 4',
    description: 'Remove rust and barnacles from hull below waterline using external diving contractor.',
    serviceProvider: 'AquaClean Marine Services Pty Ltd',
    workOrderRef: 'WO-2026-HULL-014',
    workLocationType: 'Onboard',
    primaryVesselId: 'VESSEL-001',
    charterWindowStart: '2026-03-10',
    charterWindowEnd: '2026-03-12',
    status: 'Composing',
    operatorOrganization: 'Northwind Marine Pty Ltd',
    masterAssuranceSetId: 'AS-02-P008-MASTER',
    readinessScore: 0,
    assetLinks: [
      {
        id: 'PAL-003',
        projectId: 'MAP-PROJ-2026-MARINE-008',
        assetType: 'Vessel',
        assetId: 'VESSEL-001',
        assetName: 'MV Pacific Endeavour',
        providerOrganization: 'Northwind Marine Pty Ltd',
        assuranceSetId: 'AS-01-V001',
        roleInProject: 'Subject vessel',
        addedAt: '2026-03-01T09:00:00Z',
        addedByPersona: 'Administrator',
      },
    ],
  },
  {
    id: 'MAP-PROJ-2026-MARINE-009',
    name: 'Southern Basin Platform Support Charter',
    projectType: 'Charter / Voyage',
    requestingOrganization: 'Southern Basin Energy Pty Ltd',
    clientOperator: 'Southern Basin Energy Pty Ltd',
    ownerOrganization: 'Southern Basin Energy Pty Ltd',
    location: 'Carnarvon Basin — Offshore Platform Alpha',
    description:
      'Client-managed charter composition for platform supply vessel support operations with nested vessel assurance sub-set.',
    charterer: 'Southern Basin Energy Pty Ltd',
    charterWindowStart: '2026-09-15',
    charterWindowEnd: '2027-09-15',
    status: 'Assurance In Progress',
    operatorOrganization: 'Southern Basin Energy Pty Ltd',
    masterAssuranceSetId: 'AS-02-P009-MASTER',
    readinessScore: 70,
    assetLinks: [
      {
        id: 'PAL-004',
        projectId: 'MAP-PROJ-2026-MARINE-009',
        assetType: 'Vessel',
        assetId: 'VESSEL-005',
        assetName: 'MV Atlantic Ocean',
        providerOrganization: 'Northwind Marine Pty Ltd',
        assuranceSetId: 'AS-2026-005',
        roleInProject: 'Platform supply vessel',
        addedAt: '2026-09-10T08:00:00Z',
        addedByPersona: 'C Admin',
      },
    ],
  },
];
