/*
  file summary: mock project charter data with cross-org asset links.
  responsibilities: seeds sample Northwind dangerous-route project with vessel + crew assurance sets.
  role in system: loaded by useMapStore on initialization.
*/

import { AssuranceSet } from '../types/assurance';
import { Project } from '../types/project';

export const PROJECT_SEED_ASSURANCE_SETS: AssuranceSet[] = [
  {
    id: 'AS-01-V008',
    title: 'MV Pacific Endeavour — Hull Fouling Removal Vetting',
    assuranceType: 'Vessel',
    subtypes: ['Vessel'],
    projectId: 'MAP-PROJ-2026-MARINE-008',
    projectName: 'Pacific Endeavour — Hull Fouling Removal',
    vesselId: 'VESSEL-001',
    vesselName: 'MV Pacific Endeavour',
    imoNumber: '9123456',
    initiatorOrg: 'Northwind Marine Pty Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterer: 'Northwind Marine Pty Ltd',
    charterWindowStart: '2026-03-10',
    charterWindowEnd: '2026-03-12',
    stage: 'Initiated',
    readinessScore: 10,
    mandatoryInspectionRequired: false,
    inspectionCompleted: false,
    requirements: [
      {
        id: 'REQ-V008-1',
        subtype: 'Vessel',
        category: 'Statutory Certificate',
        title: 'Certificate of Class',
        isMandatory: true,
        isFulfilled: false,
        ocrConfidence: 0,
        verifierStatus: 'Pending',
      },
    ],
    createdByPersona: 'Administrator',
  },
  {
    id: 'AS-SBE-012-V001',
    title: 'MV Atlantic Ocean — Platform Alpha Supply Vetting',
    assuranceType: 'Vessel',
    subtypes: ['Vessel'],
    projectId: 'MAP-PROJ-2026-MARINE-012',
    projectName: 'Platform Alpha Security & Supply',
    vesselId: 'VESSEL-005',
    vesselName: 'MV Atlantic Ocean',
    imoNumber: '9712044',
    initiatorOrg: 'Southern Basin Energy Pty Ltd',
    initiatorRole: 'C Admin · Client Created',
    charterer: 'Southern Basin Energy Pty Ltd',
    clientOrg: 'Southern Basin Energy Pty Ltd',
    serviceProviderOrg: 'Northwind Marine Pty Ltd',
    charterWindowStart: '2026-10-01',
    charterWindowEnd: '2027-04-01',
    stage: 'Verification',
    readinessScore: 55,
    mandatoryInspectionRequired: true,
    inspectionCompleted: false,
    requirements: [
      {
        id: 'REQ-SBE-012-V1',
        subtype: 'Vessel',
        category: 'Statutory Certificate',
        title: 'Certificate of Class',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 95,
        verifierStatus: 'Verified',
      },
      {
        id: 'REQ-SBE-012-V2',
        subtype: 'Vessel',
        category: 'Statutory Certificate',
        title: 'Cargo Ship Safety Equipment',
        isMandatory: true,
        isFulfilled: false,
        ocrConfidence: 0,
        verifierStatus: 'Pending',
      },
    ],
    createdByPersona: 'C Admin',
  },
  {
    id: 'AS-01-V001',
    title: 'MV Pacific Endeavour — Vessel Charter Vetting',
    assuranceType: 'Vessel',
    subtypes: ['Vessel'],
    vesselId: 'VESSEL-001',
    vesselName: 'MV Pacific Endeavour',
    imoNumber: '9123456',
    initiatorOrg: 'Northwind Marine Pty Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterer: 'Northwind Marine Pty Ltd',
    charterWindowStart: '2026-11-01',
    charterWindowEnd: '2027-02-28',
    stage: 'Verification',
    readinessScore: 78,
    mandatoryInspectionRequired: true,
    inspectionCompleted: false,
    requirements: [
      {
        id: 'REQ-V001-1',
        subtype: 'Vessel',
        category: 'Statutory Certificate',
        title: 'Cert1 — Certificate of Class',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 98,
        verifierStatus: 'Verified',
      },
      {
        id: 'REQ-V001-2',
        subtype: 'Vessel',
        category: 'Statutory Certificate',
        title: 'Cert2 — Cargo Ship Safety Equipment',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 96,
        verifierStatus: 'Verified',
      },
      {
        id: 'REQ-V001-3',
        subtype: 'Vessel',
        category: 'Environmental Certificate',
        title: 'Cert3 — IOPP Certificate Annex I',
        isMandatory: true,
        isFulfilled: false,
        ocrConfidence: 0,
        verifierStatus: 'Pending',
      },
    ],
    createdByPersona: 'Administrator',
  },
  {
    id: 'AS-01-C001',
    title: 'Capt. Alexander Wright — Crew Charter Vetting',
    assuranceType: 'Crew',
    subtypes: ['Crew'],
    vesselId: 'VESSEL-001',
    vesselName: 'MV Pacific Endeavour',
    imoNumber: '9123456',
    crewId: 'CREW-101',
    crewName: 'Capt. Alexander Wright',
    initiatorOrg: 'Northwind Marine Pty Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterer: 'Northwind Marine Pty Ltd',
    charterWindowStart: '2026-11-01',
    charterWindowEnd: '2027-02-28',
    stage: 'Certified',
    clientWorkflowStage: 'approved',
    approverDecision: 'Approved',
    readinessScore: 92,
    mandatoryInspectionRequired: false,
    inspectionCompleted: false,
    requirements: [
      {
        id: 'REQ-C001-1',
        subtype: 'Crew',
        category: 'Crew Credential',
        title: 'CrewCert1 — STCW Master CoC Endorsement',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 99,
        verifierStatus: 'Verified',
      },
      {
        id: 'REQ-C001-2',
        subtype: 'Crew',
        category: 'Medical Fitness Certificate',
        title: 'CrewCert2 — ENG1 Medical Fitness',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 97,
        verifierStatus: 'Verified',
      },
    ],
    createdByPersona: 'Administrator',
  },
  {
    id: 'AS-02-C002-1',
    title: 'Armed Security Team — Project Charter Vetting',
    assuranceType: 'Crew',
    subtypes: ['Crew'],
    vesselId: 'VESSEL-001',
    vesselName: 'MV Pacific Endeavour',
    imoNumber: '9123456',
    crewId: 'CREW-104',
    crewName: 'Bosun David Kowalski',
    initiatorOrg: 'Gulf Security Services Pty Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterer: 'Northwind Marine Pty Ltd',
    charterWindowStart: '2026-11-01',
    charterWindowEnd: '2027-02-28',
    stage: 'Initiated',
    readinessScore: 45,
    mandatoryInspectionRequired: false,
    inspectionCompleted: false,
    requirements: [
      {
        id: 'REQ-C002-1',
        subtype: 'Crew',
        category: 'Crew Custom Requirement',
        title: 'Armed Guard License & Firearms Endorsement',
        isMandatory: true,
        isFulfilled: false,
        ocrConfidence: 0,
        verifierStatus: 'Pending',
      },
    ],
    createdByPersona: 'Administrator',
  },
  {
    id: 'AS-SBE-010-V001',
    title: 'MV Kimberley Guardian — ERRV Charter Vetting',
    assuranceType: 'Vessel',
    subtypes: ['Vessel'],
    vesselId: 'VESSEL-006',
    vesselName: 'MV Kimberley Guardian',
    imoNumber: '9823109',
    initiatorOrg: 'Northwind Marine Pty Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterer: 'Southern Basin Energy Pty Ltd',
    clientOrg: 'Southern Basin Energy Pty Ltd',
    serviceProviderOrg: 'Northwind Marine Pty Ltd',
    charterWindowStart: '2026-11-15',
    charterWindowEnd: '2027-05-15',
    stage: 'Validation',
    readinessScore: 40,
    mandatoryInspectionRequired: true,
    inspectionCompleted: false,
    requirements: [
      {
        id: 'REQ-SBE-010-1',
        subtype: 'Vessel',
        category: 'Statutory Certificate',
        title: 'Certificate of Class',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 94,
        verifierStatus: 'Pending',
      },
    ],
    createdByPersona: 'C Admin',
  },
  {
    id: 'AS-SBE-011-V001',
    title: 'MV Ningaloo Voyager — Otway Supply Run Vetting',
    assuranceType: 'Vessel',
    subtypes: ['Vessel'],
    vesselId: 'VESSEL-007',
    vesselName: 'MV Ningaloo Voyager',
    imoNumber: '9910482',
    initiatorOrg: 'Northwind Marine Pty Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterer: 'Southern Basin Energy Pty Ltd',
    clientOrg: 'Southern Basin Energy Pty Ltd',
    serviceProviderOrg: 'Northwind Marine Pty Ltd',
    charterWindowStart: '2026-12-01',
    charterWindowEnd: '2027-06-01',
    stage: 'Initiated',
    readinessScore: 40,
    mandatoryInspectionRequired: true,
    inspectionCompleted: false,
    requirements: [
      {
        id: 'REQ-SBE-011-1',
        subtype: 'Vessel',
        category: 'Statutory Certificate',
        title: 'Certificate of Class',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 92,
        verifierStatus: 'Pending',
      },
    ],
    createdByPersona: 'C Admin',
  },
  {
    id: 'AS-SBE-012-C001',
    title: 'Gulf Security Team — Platform Escort Vetting',
    assuranceType: 'Crew',
    subtypes: ['Crew'],
    crewId: 'CREW-104',
    crewName: 'Bosun David Kowalski',
    initiatorOrg: 'Gulf Security Services Pty Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterer: 'Southern Basin Energy Pty Ltd',
    clientOrg: 'Southern Basin Energy Pty Ltd',
    serviceProviderOrg: 'Gulf Security Services Pty Ltd',
    charterWindowStart: '2026-10-01',
    charterWindowEnd: '2027-04-01',
    stage: 'Verification',
    readinessScore: 55,
    mandatoryInspectionRequired: false,
    inspectionCompleted: false,
    requirements: [
      {
        id: 'REQ-SBE-012-1',
        subtype: 'Crew',
        category: 'Crew Custom Requirement',
        title: 'Armed Guard License & Firearms Endorsement',
        isMandatory: true,
        isFulfilled: false,
        ocrConfidence: 0,
        verifierStatus: 'Pending',
      },
    ],
    createdByPersona: 'C Admin',
    vesselId: '',
    vesselName: '',
    imoNumber: ''
  },
  {
    id: 'AS-EQP-007-01',
    title: 'Schilling ROV System Mobilization Assurance',
    assuranceType: 'Equipment',
    subtypes: ['Equipment'],
    equipmentId: 'EQ-007',
    equipmentName: 'Subsea Work-Class ROV & 150T Traction Winch',
    vesselId: 'VESSEL-001',
    vesselName: 'MV Pacific Endeavour',
    imoNumber: '9123456',
    initiatorOrg: 'Northwind Marine Pty Ltd',
    initiatorRole: 'Vessel Provider Admin',
    charterWindowStart: '2026-11-01',
    charterWindowEnd: '2027-05-01',
    stage: 'Certified',
    readinessScore: 100,
    mandatoryInspectionRequired: true,
    inspectionCompleted: true,
    clientWorkflowStage: 'approved',
    requirements: [
      {
        id: 'REQ-EQP-007-SEED-1',
        category: 'Equipment Register',
        title: 'DNV Lifting Appliance Survey & Load Test',
        isMandatory: true,
        isFulfilled: true,
        ocrConfidence: 97,
        verifierStatus: 'Verified',
      },
    ],
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'MAP-PROJ-2026-MARINE-007',
    name: 'Northwind Dangerous Route Transit',
    projectType: 'Charter / Voyage',
    requestingOrganization: 'Northwind Marine Pty Ltd',
    clientOperator: 'Northwind Marine Pty Ltd',
    location: 'Timor Sea — High-Risk Transit Corridor',
    description: 'Multi-org charter composition for elevated-risk offshore transit with armed security detail.',
    charterer: 'Northwind Marine Pty Ltd',
    routeDescription: 'Dangerous route via Timor Passage — armed escort required for piracy-risk sector.',
    riskProfile: 'Armed Escort Required',
    charterWindowStart: '2026-11-01',
    charterWindowEnd: '2027-02-28',
    status: 'Assurance In Progress',
    operatorOrganization: 'Northwind Marine Pty Ltd',
    readinessScore: 45,
    assetLinks: [
      {
        id: 'PAL-001',
        projectId: 'MAP-PROJ-2026-MARINE-007',
        assetType: 'Vessel',
        assetId: 'VESSEL-001',
        assetName: 'MV Pacific Endeavour',
        providerOrganization: 'Northwind Marine Pty Ltd',
        assuranceSetId: 'AS-01-V001',
        roleInProject: 'Subject vessel',
        addedAt: '2026-09-15T08:00:00Z',
        addedByPersona: 'Administrator',
      },
      {
        id: 'PAL-002',
        projectId: 'MAP-PROJ-2026-MARINE-007',
        assetType: 'Crew',
        assetId: 'CREW-101',
        assetName: 'Capt. Alexander Wright',
        providerOrganization: 'Northwind Marine Pty Ltd',
        assuranceSetId: 'AS-01-C001',
        roleInProject: 'Master / command crew',
        addedAt: '2026-09-15T08:05:00Z',
        addedByPersona: 'Administrator',
      },
    ],
  },
  {
    id: 'MAP-PROJ-2026-MARINE-008',
    name: 'Pacific Endeavour — Hull Fouling Removal',
    projectType: 'Service Engagement',
    requestingOrganization: 'Northwind Marine Pty Ltd',
    clientOperator: 'Northwind Marine Pty Ltd',
    location: 'Fremantle Inner Harbour — Berth 4',
    description: 'Remove rust and barnacles from hull below waterline using external diving contractor.',
    serviceProvider: 'AquaClean Marine Services Pty Ltd',
    workOrderRef: 'WO-2026-HULL-014',
    workLocationType: 'Onboard',
    primaryVesselId: 'VESSEL-001',
    charterWindowStart: '2026-03-10',
    charterWindowEnd: '2026-03-12',
    status: 'Composing',
    operatorOrganization: 'Northwind Marine Pty Ltd',
    readinessScore: 0,
    assetLinks: [
      {
        id: 'PAL-003',
        projectId: 'MAP-PROJ-2026-MARINE-008',
        assetType: 'Vessel',
        assetId: 'VESSEL-001',
        assetName: 'MV Pacific Endeavour',
        providerOrganization: 'Northwind Marine Pty Ltd',
        assuranceSetId: 'AS-01-V008',
        roleInProject: 'Subject vessel',
        addedAt: '2026-03-01T09:00:00Z',
        addedByPersona: 'Administrator',
      },
    ],
  },
  {
    id: 'MAP-PROJ-2026-MARINE-009',
    name: 'Southern Basin Platform Support Charter',
    projectType: 'Charter / Voyage',
    requestingOrganization: 'Southern Basin Energy Pty Ltd',
    clientOperator: 'Southern Basin Energy Pty Ltd',
    ownerOrganization: 'Southern Basin Energy Pty Ltd',
    location: 'Carnarvon Basin — Offshore Platform Alpha',
    description:
      'Client-managed charter composition for platform supply vessel support operations with nested vessel assurance sub-set.',
    charterer: 'Southern Basin Energy Pty Ltd',
    charterWindowStart: '2026-09-15',
    charterWindowEnd: '2027-09-15',
    status: 'Assurance In Progress',
    operatorOrganization: 'Southern Basin Energy Pty Ltd',
    readinessScore: 70,
    assetLinks: [
      {
        id: 'PAL-004',
        projectId: 'MAP-PROJ-2026-MARINE-009',
        assetType: 'Vessel',
        assetId: 'VESSEL-005',
        assetName: 'MV Atlantic Ocean',
        providerOrganization: 'Northwind Marine Pty Ltd',
        assuranceSetId: 'AS-2026-005',
        roleInProject: 'Platform supply vessel',
        addedAt: '2026-09-10T08:00:00Z',
        addedByPersona: 'C Admin',
      },
    ],
  },
  {
    id: 'MAP-PROJ-2026-MARINE-010',
    name: 'Carnarvon ERRV Standby Charter',
    projectType: 'Charter / Voyage',
    requestingOrganization: 'Southern Basin Energy Pty Ltd',
    clientOperator: 'Southern Basin Energy Pty Ltd',
    ownerOrganization: 'Southern Basin Energy Pty Ltd',
    location: 'Carnarvon Basin — Offshore ERRV Standby Zone',
    description:
      'Client-managed emergency response and rescue vessel charter with Northwind Marine ERRV support.',
    charterer: 'Southern Basin Energy Pty Ltd',
    routeDescription: 'Carnarvon Basin standby patrol — platform Alpha to Beta corridor.',
    riskProfile: 'Elevated',
    charterWindowStart: '2026-11-15',
    charterWindowEnd: '2027-05-15',
    status: 'Assurance In Progress',
    operatorOrganization: 'Southern Basin Energy Pty Ltd',
    readinessScore: 40,
    assetLinks: [
      {
        id: 'PAL-010',
        projectId: 'MAP-PROJ-2026-MARINE-010',
        assetType: 'Vessel',
        assetId: 'VESSEL-006',
        assetName: 'MV Kimberley Guardian',
        providerOrganization: 'Northwind Marine Pty Ltd',
        assuranceSetId: 'AS-SBE-010-V001',
        roleInProject: 'Emergency response & rescue vessel',
        addedAt: '2026-10-01T08:00:00Z',
        addedByPersona: 'C Admin',
      },
    ],
  },
  {
    id: 'MAP-PROJ-2026-MARINE-011',
    name: 'Otway Basin Supply Run',
    projectType: 'Service Engagement',
    requestingOrganization: 'Southern Basin Energy Pty Ltd',
    clientOperator: 'Southern Basin Energy Pty Ltd',
    ownerOrganization: 'Southern Basin Energy Pty Ltd',
    location: 'Otway Basin — Offshore Supply Route',
    description:
      'Periodic platform supply run using external Northwind Marine PSV for Otway field operations.',
    serviceProvider: 'Northwind Marine Pty Ltd',
    workOrderRef: 'WO-SBE-2026-OTW-003',
    workLocationType: 'Onboard',
    primaryVesselId: 'VESSEL-007',
    charterWindowStart: '2026-12-01',
    charterWindowEnd: '2027-06-01',
    status: 'Composing',
    operatorOrganization: 'Southern Basin Energy Pty Ltd',
    readinessScore: 40,
    assetLinks: [
      {
        id: 'PAL-011',
        projectId: 'MAP-PROJ-2026-MARINE-011',
        assetType: 'Vessel',
        assetId: 'VESSEL-007',
        assetName: 'MV Ningaloo Voyager',
        providerOrganization: 'Northwind Marine Pty Ltd',
        assuranceSetId: 'AS-SBE-011-V001',
        roleInProject: 'Platform supply vessel',
        addedAt: '2026-10-03T09:00:00Z',
        addedByPersona: 'C Admin',
      },
    ],
  },
  {
    id: 'MAP-PROJ-2026-MARINE-012',
    name: 'Platform Alpha Security & Supply',
    projectType: 'Mixed / Composite',
    requestingOrganization: 'Southern Basin Energy Pty Ltd',
    clientOperator: 'Southern Basin Energy Pty Ltd',
    ownerOrganization: 'Southern Basin Energy Pty Ltd',
    location: 'Carnarvon Basin — Platform Alpha',
    description:
      'Composite project combining platform supply vessel support and external armed security crew for high-risk operations.',
    charterer: 'Southern Basin Energy Pty Ltd',
    serviceProvider: 'Northwind Marine Pty Ltd',
    riskProfile: 'High-Risk',
    charterWindowStart: '2026-10-01',
    charterWindowEnd: '2027-04-01',
    status: 'Assurance In Progress',
    operatorOrganization: 'Southern Basin Energy Pty Ltd',
    readinessScore: 55,
    assetLinks: [
      {
        id: 'PAL-012A',
        projectId: 'MAP-PROJ-2026-MARINE-012',
        assetType: 'Vessel',
        assetId: 'VESSEL-005',
        assetName: 'MV Atlantic Ocean',
        providerOrganization: 'Northwind Marine Pty Ltd',
        assuranceSetId: 'AS-SBE-012-V001',
        roleInProject: 'Platform supply vessel',
        addedAt: '2026-09-28T08:00:00Z',
        addedByPersona: 'C Admin',
      },
      {
        id: 'PAL-012B',
        projectId: 'MAP-PROJ-2026-MARINE-012',
        assetType: 'Crew',
        assetId: 'CREW-104',
        assetName: 'Bosun David Kowalski',
        providerOrganization: 'Gulf Security Services Pty Ltd',
        assuranceSetId: 'AS-SBE-012-C001',
        roleInProject: 'Armed security detail',
        addedAt: '2026-09-28T08:15:00Z',
        addedByPersona: 'C Admin',
      },
    ],
  },
  {
    id: 'MAP-PROJ-2026-MARINE-013',
    name: 'Gorgon Subsea Equipment Rental & Testing',
    projectType: 'Equipment Rental',
    requestingOrganization: 'Chevron Australia Pty Ltd',
    clientOperator: 'Chevron Australia Pty Ltd',
    ownerOrganization: 'Chevron Australia Pty Ltd',
    location: 'Dampier Shorebase & Gorgon Field',
    description: 'Deepwater SURF ROV tooling and active heave crane deployment for subsea manifold installation.',
    charterer: 'Chevron Australia Pty Ltd',
    riskProfile: 'Standard',
    workLocationType: 'Offshore',
    charterWindowStart: '2026-11-01',
    charterWindowEnd: '2027-05-01',
    status: 'Ready for Charter',
    operatorOrganization: 'Chevron Australia Pty Ltd',
    readinessScore: 100,
    assetLinks: [
      {
        id: 'PAL-013A',
        projectId: 'MAP-PROJ-2026-MARINE-013',
        assetType: 'Equipment',
        assetId: 'EQ-007',
        assetName: 'Subsea Work-Class ROV & 150T Traction Winch',
        providerOrganization: 'Northwind Marine Pty Ltd',
        assuranceSetId: 'AS-EQP-007-01',
        roleInProject: 'Primary subsea ROV spread',
        addedAt: '2026-10-01T08:00:00Z',
        addedByPersona: 'C Admin',
      },
      {
        id: 'PAL-013B',
        projectId: 'MAP-PROJ-2026-MARINE-013',
        assetType: 'Equipment',
        assetId: 'EQ-005',
        assetName: 'Offshore Pedestal Crane #1 (150T Active Heave)',
        providerOrganization: 'Northwind Marine Pty Ltd',
        assuranceSetId: 'AS-EQP-005-01',
        roleInProject: 'Heavy subsea lift crane',
        addedAt: '2026-10-01T08:10:00Z',
        addedByPersona: 'C Admin',
      },
    ],
  },
  {
    id: 'MAP-PROJ-2026-MARINE-014',
    name: 'Prelude FLNG Specialized Crew Provision',
    projectType: 'Crew Provision',
    requestingOrganization: 'Shell Australia Pty Ltd',
    clientOperator: 'Shell Australia Pty Ltd',
    ownerOrganization: 'Shell Australia Pty Ltd',
    location: 'Browse Basin — Prelude FLNG Facility',
    description: 'Certified saturation diving and dynamic positioning specialist crew deployment for annual turret maintenance.',
    charterer: 'Shell Australia Pty Ltd',
    riskProfile: 'Elevated',
    workLocationType: 'Mixed',
    charterWindowStart: '2027-01-15',
    charterWindowEnd: '2027-07-15',
    status: 'Draft',
    operatorOrganization: 'Shell Australia Pty Ltd',
    readinessScore: 25,
    assetLinks: [
      {
        id: 'PAL-014A',
        projectId: 'MAP-PROJ-2026-MARINE-014',
        assetType: 'Crew',
        assetId: 'CREW-102',
        assetName: 'Chief Eng. Marcus Sterling',
        providerOrganization: 'Northwind Marine Pty Ltd',
        assuranceSetId: 'AS-CRW-102-01',
        roleInProject: 'Chief Engineer / Technical Lead',
        addedAt: '2026-10-05T09:00:00Z',
        addedByPersona: 'C Admin',
      },
    ],
  },
  {
    id: 'MAP-PROJ-2026-MARINE-015',
    name: 'Browse Basin Annual Assurance Campaign',
    projectType: 'Assurance Campaign',
    requestingOrganization: 'Woodside Energy Ltd',
    clientOperator: 'Woodside Energy Ltd',
    ownerOrganization: 'Woodside Energy Ltd',
    location: 'Browse Basin — Torosa & Brecknock Fields',
    description: 'Comprehensive multi-vessel statutory compliance verification and environmental safety campaign.',
    charterer: 'Woodside Energy Ltd',
    riskProfile: 'Standard',
    workLocationType: 'Shoreside',
    charterWindowStart: '2025-06-01',
    charterWindowEnd: '2026-05-31',
    status: 'Closed',
    operatorOrganization: 'Woodside Energy Ltd',
    readinessScore: 100,
    assetLinks: [
      {
        id: 'PAL-015A',
        projectId: 'MAP-PROJ-2026-MARINE-015',
        assetType: 'Vessel',
        assetId: 'VESSEL-004',
        assetName: 'MV Southern Cross',
        providerOrganization: 'Northwind Marine Pty Ltd',
        assuranceSetId: 'AS-2026-004',
        roleInProject: 'Subsea support vessel',
        addedAt: '2025-05-20T08:00:00Z',
        addedByPersona: 'C Admin',
      },
    ],
  },
];
